# Generated by roxyassert: do not edit by hand.
# Re-generated on devtools::document(). Commit this file like NAMESPACE.

assert_return_AlpacaAccount__get_account <- function(value) {
  assert_data_table(value)
  return(value)
}

assert_return_AlpacaAccount__get_account_config <- function(value) {
  assert_data_table(value)
  return(value)
}

assert_args_AlpacaAccount__modify_account_config <- function(dtbp_check, no_shorting, suspend_trade, trade_confirm_email, fractional_trading, max_margin_multiplier, pdt_check, max_options_trading_level, ptp_no_exception_entry, disable_overnight_trading) {
  if (!is.null(dtbp_check)) {
    assert_scalar_character(dtbp_check)
  }
  if (!is.null(no_shorting)) {
    assert_scalar_logical(no_shorting)
  }
  if (!is.null(suspend_trade)) {
    assert_scalar_logical(suspend_trade)
  }
  if (!is.null(trade_confirm_email)) {
    assert_scalar_character(trade_confirm_email)
  }
  if (!is.null(fractional_trading)) {
    assert_scalar_logical(fractional_trading)
  }
  if (!is.null(max_margin_multiplier)) {
    assert_scalar_character(max_margin_multiplier)
  }
  if (!is.null(pdt_check)) {
    assert_scalar_character(pdt_check)
  }
  if (!is.null(max_options_trading_level)) {
    assert_scalar_count(max_options_trading_level)
    assert_between(max_options_trading_level, lower = 0)
  }
  if (!is.null(ptp_no_exception_entry)) {
    assert_scalar_logical(ptp_no_exception_entry)
  }
  if (!is.null(disable_overnight_trading)) {
    assert_scalar_logical(disable_overnight_trading)
  }
  return(invisible(NULL))
}

assert_return_AlpacaAccount__modify_account_config <- function(value) {
  assert_data_table(value)
  return(value)
}

assert_return_AlpacaAccount__get_positions <- function(value) {
  assert_data_table(value)
  return(value)
}

assert_args_AlpacaAccount__get_position <- function(symbol_or_id) {
  assert_scalar_character(symbol_or_id)
  return(invisible(NULL))
}

assert_return_AlpacaAccount__get_position <- function(value) {
  assert_data_table(value)
  return(value)
}

assert_args_AlpacaAccount__close_position <- function(symbol_or_id, qty, percentage) {
  assert_scalar_character(symbol_or_id)
  if (!is.null(qty)) {
    assert_scalar_double(qty)
  }
  if (!is.null(percentage)) {
    assert_scalar_double(percentage)
  }
  return(invisible(NULL))
}

assert_return_AlpacaAccount__close_position <- function(value) {
  assert_data_table(value)
  return(value)
}

assert_args_AlpacaAccount__close_all_positions <- function(cancel_orders) {
  assert_scalar_logical(cancel_orders)
  return(invisible(NULL))
}

assert_return_AlpacaAccount__close_all_positions <- function(value) {
  assert_data_table(value)
  return(value)
}

assert_args_AlpacaAccount__exercise_option <- function(symbol_or_id) {
  assert_scalar_character(symbol_or_id)
  return(invisible(NULL))
}

assert_return_AlpacaAccount__exercise_option <- function(value) {
  assert_data_table(value)
  return(value)
}

assert_args_AlpacaAccount__get_portfolio_history <- function(period, timeframe, start, end, intraday_reporting, pnl_reset, date_start, date_end) {
  if (!is.null(period)) {
    assert_scalar_character(period)
  }
  if (!is.null(timeframe)) {
    assert_scalar_character(timeframe)
  }
  if (!is.null(start)) {
    assert_scalar_character(start)
  }
  if (!is.null(end)) {
    assert_scalar_character(end)
  }
  if (!is.null(intraday_reporting)) {
    assert_scalar_character(intraday_reporting)
  }
  if (!is.null(pnl_reset)) {
    assert_scalar_character(pnl_reset)
  }
  if (!is.null(date_start)) {
    assert_scalar_character(date_start)
  }
  if (!is.null(date_end)) {
    assert_scalar_character(date_end)
  }
  return(invisible(NULL))
}

assert_return_AlpacaAccount__get_portfolio_history <- function(value) {
  assert_data_table(value)
  return(value)
}

assert_args_AlpacaAccount__get_activities <- function(activity_types, category, date, until, after, direction, page_token) {
  if (!is.null(activity_types)) {
    assert_scalar_character(activity_types)
  }
  if (!is.null(category)) {
    assert_scalar_character(category)
  }
  if (!is.null(date)) {
    assert_scalar_character(date)
  }
  if (!is.null(until)) {
    assert_scalar_character(until)
  }
  if (!is.null(after)) {
    assert_scalar_character(after)
  }
  if (!is.null(direction)) {
    assert_scalar_character(direction)
  }
  if (!is.null(page_token)) {
    assert_scalar_character(page_token)
  }
  return(invisible(NULL))
}

assert_return_AlpacaAccount__get_activities <- function(value) {
  assert_data_table(value)
  return(value)
}

assert_args_AlpacaAccount__get_activities_by_type <- function(activity_type, date, until, after, direction, page_token) {
  assert_scalar_character(activity_type)
  if (!is.null(date)) {
    assert_scalar_character(date)
  }
  if (!is.null(until)) {
    assert_scalar_character(until)
  }
  if (!is.null(after)) {
    assert_scalar_character(after)
  }
  if (!is.null(direction)) {
    assert_scalar_character(direction)
  }
  if (!is.null(page_token)) {
    assert_scalar_character(page_token)
  }
  return(invisible(NULL))
}

assert_return_AlpacaAccount__get_activities_by_type <- function(value) {
  assert_data_table(value)
  return(value)
}

assert_return_AlpacaAccount__get_watchlists <- function(value) {
  assert_data_table(value)
  return(value)
}

assert_args_AlpacaAccount__get_watchlist <- function(watchlist_id) {
  assert_scalar_character(watchlist_id)
  return(invisible(NULL))
}

assert_return_AlpacaAccount__get_watchlist <- function(value) {
  assert_data_table(value)
  return(value)
}

assert_args_AlpacaAccount__add_watchlist <- function(name, symbols) {
  assert_scalar_character(name)
  if (!is.null(symbols)) {
    assert_character(symbols)
    assert_no_missing_values(symbols)
  }
  return(invisible(NULL))
}

assert_return_AlpacaAccount__add_watchlist <- function(value) {
  assert_data_table(value)
  return(value)
}

assert_args_AlpacaAccount__modify_watchlist <- function(watchlist_id, name, symbols) {
  assert_scalar_character(watchlist_id)
  assert_scalar_character(name)
  assert_character(symbols)
  assert_no_missing_values(symbols)
  return(invisible(NULL))
}

assert_return_AlpacaAccount__modify_watchlist <- function(value) {
  assert_data_table(value)
  return(value)
}

assert_args_AlpacaAccount__add_watchlist_symbol <- function(watchlist_id, symbol) {
  assert_scalar_character(watchlist_id)
  assert_scalar_character(symbol)
  return(invisible(NULL))
}

assert_return_AlpacaAccount__add_watchlist_symbol <- function(value) {
  assert_data_table(value)
  return(value)
}

assert_args_AlpacaAccount__cancel_watchlist_symbol <- function(watchlist_id, symbol) {
  assert_scalar_character(watchlist_id)
  assert_scalar_character(symbol)
  return(invisible(NULL))
}

assert_return_AlpacaAccount__cancel_watchlist_symbol <- function(value) {
  assert_data_table(value)
  return(value)
}

assert_args_AlpacaAccount__cancel_watchlist <- function(watchlist_id) {
  assert_scalar_character(watchlist_id)
  return(invisible(NULL))
}

assert_return_AlpacaAccount__cancel_watchlist <- function(value) {
  assert_data_table(value)
  return(value)
}

assert_args_AlpacaBase__initialize <- function(keys, base_url, async) {
  assert_list(keys)
  assert_scalar_character(base_url)
  assert_scalar_logical(async)
  return(invisible(NULL))
}

assert_return_AlpacaBase__initialize <- function(value) {
  assert_class(value, "AlpacaBase")
  return(value)
}

assert_args_AlpacaMarketData__initialize <- function(keys, base_url, data_base_url, async) {
  assert_list(keys)
  assert_scalar_character(base_url)
  assert_scalar_character(data_base_url)
  assert_scalar_logical(async)
  return(invisible(NULL))
}

assert_return_AlpacaMarketData__initialize <- function(value) {
  assert_class(value, "AlpacaMarketData")
  return(value)
}

assert_args_AlpacaMarketData__get_bars <- function(symbol, timeframe, start, end, limit, adjustment, asof, feed, currency, sort, page_token, max_pages, sleep) {
  assert_scalar_character(symbol)
  assert_scalar_character(timeframe)
  if (!is.null(start)) {
    assert_scalar_character(start)
  }
  if (!is.null(end)) {
    assert_scalar_character(end)
  }
  if (!is.null(limit)) {
    assert_scalar_count(limit)
    assert_between(limit, lower = 1, upper = 10000)
  }
  if (!is.null(adjustment)) {
    assert_scalar_character(adjustment)
  }
  if (!is.null(asof)) {
    assert_scalar_character(asof)
  }
  if (!is.null(feed)) {
    assert_scalar_character(feed)
  }
  if (!is.null(currency)) {
    assert_scalar_character(currency)
  }
  if (!is.null(sort)) {
    assert_scalar_character(sort)
  }
  if (!is.null(page_token)) {
    assert_scalar_character(page_token)
  }
  assert_any_of(
    max_pages,
    function(.x) {
      assert_scalar_double(.x)
      assert_between(.x, lower = 1)
    },
    function(.x) {
      assert_scalar_integer(.x)
      assert_between(.x, lower = 1)
    }
  )
  assert_scalar_double(sleep)
  assert_between(sleep, lower = 0, upper = Inf, upper_inclusive = FALSE)
  return(invisible(NULL))
}

assert_return_AlpacaMarketData__get_bars <- function(value) {
  assert_data_table(value)
  return(value)
}

assert_args_AlpacaMarketData__get_bars_multi <- function(symbols, timeframe, start, end, limit, adjustment, asof, feed, currency, sort, page_token, max_pages, sleep) {
  assert_character(symbols)
  assert_no_missing_values(symbols)
  assert_scalar_character(timeframe)
  if (!is.null(start)) {
    assert_scalar_character(start)
  }
  if (!is.null(end)) {
    assert_scalar_character(end)
  }
  if (!is.null(limit)) {
    assert_scalar_count(limit)
    assert_between(limit, lower = 1, upper = 10000)
  }
  if (!is.null(adjustment)) {
    assert_scalar_character(adjustment)
  }
  if (!is.null(asof)) {
    assert_scalar_character(asof)
  }
  if (!is.null(feed)) {
    assert_scalar_character(feed)
  }
  if (!is.null(currency)) {
    assert_scalar_character(currency)
  }
  if (!is.null(sort)) {
    assert_scalar_character(sort)
  }
  if (!is.null(page_token)) {
    assert_scalar_character(page_token)
  }
  assert_any_of(
    max_pages,
    function(.x) {
      assert_scalar_double(.x)
      assert_between(.x, lower = 1)
    },
    function(.x) {
      assert_scalar_integer(.x)
      assert_between(.x, lower = 1)
    }
  )
  assert_scalar_double(sleep)
  assert_between(sleep, lower = 0, upper = Inf, upper_inclusive = FALSE)
  return(invisible(NULL))
}

assert_return_AlpacaMarketData__get_bars_multi <- function(value) {
  assert_data_table(value)
  return(value)
}

assert_args_AlpacaMarketData__get_latest_bar <- function(symbol, feed) {
  assert_scalar_character(symbol)
  if (!is.null(feed)) {
    assert_scalar_character(feed)
  }
  return(invisible(NULL))
}

assert_return_AlpacaMarketData__get_latest_bar <- function(value) {
  assert_data_table(value)
  return(value)
}

assert_args_AlpacaMarketData__get_latest_trade <- function(symbol, feed, currency) {
  assert_scalar_character(symbol)
  if (!is.null(feed)) {
    assert_scalar_character(feed)
  }
  if (!is.null(currency)) {
    assert_scalar_character(currency)
  }
  return(invisible(NULL))
}

assert_return_AlpacaMarketData__get_latest_trade <- function(value) {
  assert_data_table(value)
  return(value)
}

assert_args_AlpacaMarketData__get_latest_quote <- function(symbol, feed, currency) {
  assert_scalar_character(symbol)
  if (!is.null(feed)) {
    assert_scalar_character(feed)
  }
  if (!is.null(currency)) {
    assert_scalar_character(currency)
  }
  return(invisible(NULL))
}

assert_return_AlpacaMarketData__get_latest_quote <- function(value) {
  assert_data_table(value)
  return(value)
}

assert_args_AlpacaMarketData__get_snapshot <- function(symbol, feed, currency) {
  assert_scalar_character(symbol)
  if (!is.null(feed)) {
    assert_scalar_character(feed)
  }
  if (!is.null(currency)) {
    assert_scalar_character(currency)
  }
  return(invisible(NULL))
}

assert_return_AlpacaMarketData__get_snapshot <- function(value) {
  assert_data_table(value)
  return(value)
}

assert_args_AlpacaMarketData__get_latest_bars_multi <- function(symbols, feed, currency) {
  assert_character(symbols)
  assert_no_missing_values(symbols)
  if (!is.null(feed)) {
    assert_scalar_character(feed)
  }
  if (!is.null(currency)) {
    assert_scalar_character(currency)
  }
  return(invisible(NULL))
}

assert_return_AlpacaMarketData__get_latest_bars_multi <- function(value) {
  assert_data_table(value)
  return(value)
}

assert_args_AlpacaMarketData__get_latest_trades_multi <- function(symbols, feed, currency) {
  assert_character(symbols)
  assert_no_missing_values(symbols)
  if (!is.null(feed)) {
    assert_scalar_character(feed)
  }
  if (!is.null(currency)) {
    assert_scalar_character(currency)
  }
  return(invisible(NULL))
}

assert_return_AlpacaMarketData__get_latest_trades_multi <- function(value) {
  assert_data_table(value)
  return(value)
}

assert_args_AlpacaMarketData__get_latest_quotes_multi <- function(symbols, feed, currency) {
  assert_character(symbols)
  assert_no_missing_values(symbols)
  if (!is.null(feed)) {
    assert_scalar_character(feed)
  }
  if (!is.null(currency)) {
    assert_scalar_character(currency)
  }
  return(invisible(NULL))
}

assert_return_AlpacaMarketData__get_latest_quotes_multi <- function(value) {
  assert_data_table(value)
  return(value)
}

assert_args_AlpacaMarketData__get_snapshots_multi <- function(symbols, feed, currency) {
  assert_character(symbols)
  assert_no_missing_values(symbols)
  if (!is.null(feed)) {
    assert_scalar_character(feed)
  }
  if (!is.null(currency)) {
    assert_scalar_character(currency)
  }
  return(invisible(NULL))
}

assert_return_AlpacaMarketData__get_snapshots_multi <- function(value) {
  assert_data_table(value)
  return(value)
}

assert_args_AlpacaMarketData__get_trades <- function(symbol, start, end, limit, asof, feed, currency, sort, page_token) {
  assert_scalar_character(symbol)
  if (!is.null(start)) {
    assert_scalar_character(start)
  }
  if (!is.null(end)) {
    assert_scalar_character(end)
  }
  if (!is.null(limit)) {
    assert_scalar_count(limit)
    assert_between(limit, lower = 1, upper = 10000)
  }
  if (!is.null(asof)) {
    assert_scalar_character(asof)
  }
  if (!is.null(feed)) {
    assert_scalar_character(feed)
  }
  if (!is.null(currency)) {
    assert_scalar_character(currency)
  }
  if (!is.null(sort)) {
    assert_scalar_character(sort)
  }
  if (!is.null(page_token)) {
    assert_scalar_character(page_token)
  }
  return(invisible(NULL))
}

assert_return_AlpacaMarketData__get_trades <- function(value) {
  assert_data_table(value)
  return(value)
}

assert_args_AlpacaMarketData__get_quotes <- function(symbol, start, end, limit, asof, feed, currency, sort, page_token) {
  assert_scalar_character(symbol)
  if (!is.null(start)) {
    assert_scalar_character(start)
  }
  if (!is.null(end)) {
    assert_scalar_character(end)
  }
  if (!is.null(limit)) {
    assert_scalar_count(limit)
    assert_between(limit, lower = 1, upper = 10000)
  }
  if (!is.null(asof)) {
    assert_scalar_character(asof)
  }
  if (!is.null(feed)) {
    assert_scalar_character(feed)
  }
  if (!is.null(currency)) {
    assert_scalar_character(currency)
  }
  if (!is.null(sort)) {
    assert_scalar_character(sort)
  }
  if (!is.null(page_token)) {
    assert_scalar_character(page_token)
  }
  return(invisible(NULL))
}

assert_return_AlpacaMarketData__get_quotes <- function(value) {
  assert_data_table(value)
  return(value)
}

assert_args_AlpacaMarketData__get_assets <- function(status, asset_class, exchange, attributes) {
  if (!is.null(status)) {
    assert_scalar_character(status)
  }
  if (!is.null(asset_class)) {
    assert_scalar_character(asset_class)
  }
  if (!is.null(exchange)) {
    assert_scalar_character(exchange)
  }
  if (!is.null(attributes)) {
    assert_scalar_character(attributes)
  }
  return(invisible(NULL))
}

assert_return_AlpacaMarketData__get_assets <- function(value) {
  assert_data_table(value)
  return(value)
}

assert_args_AlpacaMarketData__get_asset <- function(symbol_or_id) {
  assert_scalar_character(symbol_or_id)
  return(invisible(NULL))
}

assert_return_AlpacaMarketData__get_asset <- function(value) {
  assert_data_table(value)
  return(value)
}

assert_args_AlpacaMarketData__get_calendar <- function(start, end, date_type) {
  if (!is.null(start)) {
    assert_scalar_character(start)
  }
  if (!is.null(end)) {
    assert_scalar_character(end)
  }
  if (!is.null(date_type)) {
    assert_scalar_character(date_type)
  }
  return(invisible(NULL))
}

assert_return_AlpacaMarketData__get_calendar <- function(value) {
  assert_data_table(value)
  return(value)
}

assert_return_AlpacaMarketData__get_clock <- function(value) {
  assert_data_table(value)
  return(value)
}

assert_args_AlpacaMarketData__get_corporate_actions <- function(ca_types, since, until, symbol, cusip, date_type) {
  assert_scalar_character(ca_types)
  assert_scalar_character(since)
  assert_scalar_character(until)
  if (!is.null(symbol)) {
    assert_scalar_character(symbol)
  }
  if (!is.null(cusip)) {
    assert_scalar_character(cusip)
  }
  if (!is.null(date_type)) {
    assert_scalar_character(date_type)
  }
  return(invisible(NULL))
}

assert_return_AlpacaMarketData__get_corporate_actions <- function(value) {
  assert_data_table(value)
  return(value)
}

assert_args_AlpacaMarketData__get_news <- function(symbols, start, end, limit, sort, include_content, exclude_contentless, page_token) {
  if (!is.null(symbols)) {
    assert_character(symbols)
    assert_no_missing_values(symbols)
  }
  if (!is.null(start)) {
    assert_scalar_character(start)
  }
  if (!is.null(end)) {
    assert_scalar_character(end)
  }
  if (!is.null(limit)) {
    assert_scalar_count(limit)
    assert_between(limit, lower = 1)
  }
  if (!is.null(sort)) {
    assert_scalar_character(sort)
  }
  if (!is.null(include_content)) {
    assert_scalar_logical(include_content)
  }
  if (!is.null(exclude_contentless)) {
    assert_scalar_logical(exclude_contentless)
  }
  if (!is.null(page_token)) {
    assert_scalar_character(page_token)
  }
  return(invisible(NULL))
}

assert_return_AlpacaMarketData__get_news <- function(value) {
  assert_data_table(value)
  return(value)
}

assert_args_AlpacaMarketData__get_crypto_orderbook <- function(symbols, loc) {
  assert_character(symbols)
  assert_no_missing_values(symbols)
  assert_scalar_character(loc)
  return(invisible(NULL))
}

assert_return_AlpacaMarketData__get_crypto_orderbook <- function(value) {
  assert_data_table(value)
  return(value)
}

assert_args_AlpacaMarketData__get_most_actives <- function(by, top) {
  if (!is.null(by)) {
    assert_scalar_character(by)
  }
  if (!is.null(top)) {
    assert_scalar_count(top)
    assert_between(top, lower = 1)
  }
  return(invisible(NULL))
}

assert_return_AlpacaMarketData__get_most_actives <- function(value) {
  assert_data_table(value)
  return(value)
}

assert_args_AlpacaMarketData__get_movers <- function(market_type, top) {
  assert_scalar_character(market_type)
  if (!is.null(top)) {
    assert_scalar_count(top)
    assert_between(top, lower = 1)
  }
  return(invisible(NULL))
}

assert_return_AlpacaMarketData__get_movers <- function(value) {
  assert_data_table(value)
  return(value)
}

assert_args_AlpacaOptions__initialize <- function(keys, base_url, data_base_url, async) {
  assert_list(keys)
  assert_scalar_character(base_url)
  assert_scalar_character(data_base_url)
  assert_scalar_logical(async)
  return(invisible(NULL))
}

assert_return_AlpacaOptions__initialize <- function(value) {
  assert_class(value, "AlpacaOptions")
  return(value)
}

assert_args_AlpacaOptions__get_contracts <- function(underlying_symbols, status, type, expiration_date, expiration_date_gte, expiration_date_lte, strike_price_gte, strike_price_lte, root_symbol, style, limit, page_token, show_deliverables, ppind) {
  if (!is.null(underlying_symbols)) {
    assert_scalar_character(underlying_symbols)
  }
  if (!is.null(status)) {
    assert_scalar_character(status)
  }
  if (!is.null(type)) {
    assert_scalar_character(type)
  }
  if (!is.null(expiration_date)) {
    assert_scalar_character(expiration_date)
  }
  if (!is.null(expiration_date_gte)) {
    assert_scalar_character(expiration_date_gte)
  }
  if (!is.null(expiration_date_lte)) {
    assert_scalar_character(expiration_date_lte)
  }
  if (!is.null(strike_price_gte)) {
    assert_scalar_double(strike_price_gte)
  }
  if (!is.null(strike_price_lte)) {
    assert_scalar_double(strike_price_lte)
  }
  if (!is.null(root_symbol)) {
    assert_scalar_character(root_symbol)
  }
  if (!is.null(style)) {
    assert_scalar_character(style)
  }
  if (!is.null(limit)) {
    assert_scalar_count(limit)
    assert_between(limit, lower = 1, upper = 10000)
  }
  if (!is.null(page_token)) {
    assert_scalar_character(page_token)
  }
  if (!is.null(show_deliverables)) {
    assert_scalar_logical(show_deliverables)
  }
  if (!is.null(ppind)) {
    assert_scalar_logical(ppind)
  }
  return(invisible(NULL))
}

assert_return_AlpacaOptions__get_contracts <- function(value) {
  assert_data_table(value)
  return(value)
}

assert_args_AlpacaOptions__get_contract <- function(symbol_or_id) {
  assert_scalar_character(symbol_or_id)
  return(invisible(NULL))
}

assert_return_AlpacaOptions__get_contract <- function(value) {
  assert_data_table(value)
  return(value)
}

assert_args_AlpacaOptions__get_option_bars <- function(symbols, timeframe, start, end, limit, page_token, sort) {
  assert_scalar_character(symbols)
  assert_scalar_character(timeframe)
  if (!is.null(start)) {
    assert_scalar_character(start)
  }
  if (!is.null(end)) {
    assert_scalar_character(end)
  }
  if (!is.null(limit)) {
    assert_scalar_count(limit)
    assert_between(limit, lower = 1, upper = 10000)
  }
  if (!is.null(page_token)) {
    assert_scalar_character(page_token)
  }
  if (!is.null(sort)) {
    assert_scalar_character(sort)
  }
  return(invisible(NULL))
}

assert_return_AlpacaOptions__get_option_bars <- function(value) {
  assert_data_table(value)
  return(value)
}

assert_args_AlpacaOptions__get_option_trades <- function(symbols, start, end, limit, page_token, sort) {
  assert_scalar_character(symbols)
  if (!is.null(start)) {
    assert_scalar_character(start)
  }
  if (!is.null(end)) {
    assert_scalar_character(end)
  }
  if (!is.null(limit)) {
    assert_scalar_count(limit)
    assert_between(limit, lower = 1, upper = 10000)
  }
  if (!is.null(page_token)) {
    assert_scalar_character(page_token)
  }
  if (!is.null(sort)) {
    assert_scalar_character(sort)
  }
  return(invisible(NULL))
}

assert_return_AlpacaOptions__get_option_trades <- function(value) {
  assert_data_table(value)
  return(value)
}

assert_args_AlpacaOptions__get_option_latest_quotes <- function(symbols, feed) {
  assert_scalar_character(symbols)
  if (!is.null(feed)) {
    assert_scalar_character(feed)
  }
  return(invisible(NULL))
}

assert_return_AlpacaOptions__get_option_latest_quotes <- function(value) {
  assert_data_table(value)
  return(value)
}

assert_args_AlpacaOptions__get_option_latest_trades <- function(symbols, feed) {
  assert_scalar_character(symbols)
  if (!is.null(feed)) {
    assert_scalar_character(feed)
  }
  return(invisible(NULL))
}

assert_return_AlpacaOptions__get_option_latest_trades <- function(value) {
  assert_data_table(value)
  return(value)
}

assert_args_AlpacaOptions__get_option_snapshots <- function(symbols, feed, updated_since, limit, page_token) {
  assert_scalar_character(symbols)
  if (!is.null(feed)) {
    assert_scalar_character(feed)
  }
  if (!is.null(updated_since)) {
    assert_scalar_character(updated_since)
  }
  if (!is.null(limit)) {
    assert_scalar_count(limit)
    assert_between(limit, lower = 1, upper = 1000)
  }
  if (!is.null(page_token)) {
    assert_scalar_character(page_token)
  }
  return(invisible(NULL))
}

assert_return_AlpacaOptions__get_option_snapshots <- function(value) {
  assert_data_table(value)
  return(value)
}

assert_args_AlpacaOptions__get_option_chain <- function(underlying_symbol, type, expiration_date, expiration_date_gte, expiration_date_lte, strike_price_gte, strike_price_lte, root_symbol, feed, limit, updated_since, page_token) {
  assert_scalar_character(underlying_symbol)
  if (!is.null(type)) {
    assert_scalar_character(type)
  }
  if (!is.null(expiration_date)) {
    assert_scalar_character(expiration_date)
  }
  if (!is.null(expiration_date_gte)) {
    assert_scalar_character(expiration_date_gte)
  }
  if (!is.null(expiration_date_lte)) {
    assert_scalar_character(expiration_date_lte)
  }
  if (!is.null(strike_price_gte)) {
    assert_scalar_double(strike_price_gte)
  }
  if (!is.null(strike_price_lte)) {
    assert_scalar_double(strike_price_lte)
  }
  if (!is.null(root_symbol)) {
    assert_scalar_character(root_symbol)
  }
  if (!is.null(feed)) {
    assert_scalar_character(feed)
  }
  if (!is.null(limit)) {
    assert_scalar_count(limit)
    assert_between(limit, lower = 1, upper = 1000)
  }
  if (!is.null(updated_since)) {
    assert_scalar_character(updated_since)
  }
  if (!is.null(page_token)) {
    assert_scalar_character(page_token)
  }
  return(invisible(NULL))
}

assert_return_AlpacaOptions__get_option_chain <- function(value) {
  assert_data_table(value)
  return(value)
}

assert_args_AlpacaTrading__add_order <- function(symbol, side, type, time_in_force, qty, notional, limit_price, stop_price, trail_price, trail_percent, extended_hours, client_order_id, order_class, take_profit, stop_loss, position_intent, legs, advanced_instructions) {
  if (!is.null(symbol)) {
    assert_scalar_character(symbol)
  }
  if (!is.null(side)) {
    assert_scalar_character(side)
  }
  assert_scalar_character(type)
  assert_scalar_character(time_in_force)
  if (!is.null(qty)) {
    assert_scalar_double(qty)
  }
  if (!is.null(notional)) {
    assert_scalar_double(notional)
  }
  if (!is.null(limit_price)) {
    assert_scalar_double(limit_price)
  }
  if (!is.null(stop_price)) {
    assert_scalar_double(stop_price)
  }
  if (!is.null(trail_price)) {
    assert_scalar_double(trail_price)
  }
  if (!is.null(trail_percent)) {
    assert_scalar_double(trail_percent)
  }
  if (!is.null(extended_hours)) {
    assert_scalar_logical(extended_hours)
  }
  if (!is.null(client_order_id)) {
    assert_scalar_character(client_order_id)
  }
  if (!is.null(order_class)) {
    assert_scalar_character(order_class)
  }
  if (!is.null(take_profit)) {
    assert_list(take_profit)
  }
  if (!is.null(stop_loss)) {
    assert_list(stop_loss)
  }
  if (!is.null(position_intent)) {
    assert_scalar_character(position_intent)
  }
  if (!is.null(legs)) {
    assert_list(legs)
  }
  if (!is.null(advanced_instructions)) {
    assert_list(advanced_instructions)
  }
  return(invisible(NULL))
}

assert_return_AlpacaTrading__add_order <- function(value) {
  assert_data_table(value)
  return(value)
}

assert_args_AlpacaTrading__get_orders <- function(status, limit, after, until, direction, nested, symbols, side, asset_class, before_order_id, after_order_id) {
  if (!is.null(status)) {
    assert_scalar_character(status)
  }
  if (!is.null(limit)) {
    assert_scalar_count(limit)
    assert_between(limit, lower = 1)
  }
  if (!is.null(after)) {
    assert_scalar_character(after)
  }
  if (!is.null(until)) {
    assert_scalar_character(until)
  }
  if (!is.null(direction)) {
    assert_scalar_character(direction)
  }
  if (!is.null(nested)) {
    assert_scalar_logical(nested)
  }
  if (!is.null(symbols)) {
    assert_scalar_character(symbols)
  }
  if (!is.null(side)) {
    assert_scalar_character(side)
  }
  if (!is.null(asset_class)) {
    assert_scalar_character(asset_class)
  }
  if (!is.null(before_order_id)) {
    assert_scalar_character(before_order_id)
  }
  if (!is.null(after_order_id)) {
    assert_scalar_character(after_order_id)
  }
  return(invisible(NULL))
}

assert_return_AlpacaTrading__get_orders <- function(value) {
  assert_data_table(value)
  return(value)
}

assert_args_AlpacaTrading__get_order <- function(order_id, nested) {
  assert_scalar_character(order_id)
  if (!is.null(nested)) {
    assert_scalar_logical(nested)
  }
  return(invisible(NULL))
}

assert_return_AlpacaTrading__get_order <- function(value) {
  assert_data_table(value)
  return(value)
}

assert_args_AlpacaTrading__get_order_by_client_id <- function(client_order_id) {
  assert_scalar_character(client_order_id)
  return(invisible(NULL))
}

assert_return_AlpacaTrading__get_order_by_client_id <- function(value) {
  assert_data_table(value)
  return(value)
}

assert_args_AlpacaTrading__modify_order <- function(order_id, qty, notional, time_in_force, limit_price, stop_price, trail, client_order_id, advanced_instructions) {
  assert_scalar_character(order_id)
  if (!is.null(qty)) {
    assert_scalar_double(qty)
  }
  if (!is.null(notional)) {
    assert_scalar_double(notional)
  }
  if (!is.null(time_in_force)) {
    assert_scalar_character(time_in_force)
  }
  if (!is.null(limit_price)) {
    assert_scalar_double(limit_price)
  }
  if (!is.null(stop_price)) {
    assert_scalar_double(stop_price)
  }
  if (!is.null(trail)) {
    assert_scalar_double(trail)
  }
  if (!is.null(client_order_id)) {
    assert_scalar_character(client_order_id)
  }
  if (!is.null(advanced_instructions)) {
    assert_list(advanced_instructions)
  }
  return(invisible(NULL))
}

assert_return_AlpacaTrading__modify_order <- function(value) {
  assert_data_table(value)
  return(value)
}

assert_args_AlpacaTrading__cancel_order <- function(order_id) {
  assert_scalar_character(order_id)
  return(invisible(NULL))
}

assert_return_AlpacaTrading__cancel_order <- function(value) {
  assert_data_table(value)
  return(value)
}

assert_return_AlpacaTrading__cancel_all_orders <- function(value) {
  assert_data_table(value)
  return(value)
}

assert_args_alpaca_backfill_bars <- function(symbols, timeframes, start, end, path, adjustment, feed, sleep, keys, data_base_url) {
  assert_character(symbols)
  assert_no_missing_values(symbols)
  assert_character(timeframes)
  assert_no_missing_values(timeframes)
  assert_any_of(
    start,
    function(.x) {
      assert_datetime(.x)
      assert_no_missing_values(.x)
    },
    function(.x) {
      assert_character(.x)
      assert_no_missing_values(.x)
    }
  )
  assert_any_of(
    end,
    function(.x) {
      assert_datetime(.x)
      assert_no_missing_values(.x)
    },
    function(.x) {
      assert_character(.x)
      assert_no_missing_values(.x)
    }
  )
  assert_scalar_character(path)
  assert_scalar_character(adjustment)
  if (!is.null(feed)) {
    assert_scalar_character(feed)
  }
  assert_scalar_double(sleep)
  assert_between(sleep, lower = 0, upper = Inf, upper_inclusive = FALSE)
  assert_list(keys)
  assert_scalar_character(data_base_url)
  return(invisible(NULL))
}

assert_return_alpaca_backfill_bars <- function(value) {
  assert_class(value, "data.table")
  return(value)
}

assert_args_wrap_list_fields <- function(x) {
  assert_list(x)
  return(invisible(NULL))
}

assert_return_wrap_list_fields <- function(value) {
  assert_list(value)
  return(value)
}

assert_args_rfc3339_to_datetime <- function(x) {
  if (!is.null(x)) {
    assert_character(x)
  }
  return(invisible(NULL))
}

assert_return_rfc3339_to_datetime <- function(value) {
  assert_datetime(value)
  return(value)
}

assert_args_coerce_cols <- function(dt, cols, fn) {
  assert_class(dt, "data.table")
  assert_character(cols)
  assert_no_missing_values(cols)
  assert_function(fn)
  return(invisible(NULL))
}

assert_return_coerce_cols <- function(value) {
  assert_class(value, "data.table")
  return(value)
}

assert_args_combine_et_datetime <- function(date, time) {
  assert_character(date)
  assert_character(time)
  return(invisible(NULL))
}

assert_return_combine_et_datetime <- function(value) {
  assert_datetime(value)
  return(value)
}

assert_args_hhmm_to_hh_mm <- function(x) {
  assert_character(x)
  return(invisible(NULL))
}

assert_return_hhmm_to_hh_mm <- function(value) {
  assert_character(value)
  return(value)
}

assert_args_parse_bars <- function(bars) {
  if (!is.null(bars)) {
    assert_list(bars)
  }
  return(invisible(NULL))
}

assert_return_parse_bars <- function(value) {
  assert_class(value, "data.table")
  return(value)
}

assert_args_parse_multi_bars_items <- function(items) {
  if (!is.null(items)) {
    assert_list(items)
  }
  return(invisible(NULL))
}

assert_return_parse_multi_bars_items <- function(value) {
  assert_class(value, "data.table")
  return(value)
}

assert_args_parse_trades <- function(trades) {
  if (!is.null(trades)) {
    assert_list(trades)
  }
  return(invisible(NULL))
}

assert_return_parse_trades <- function(value) {
  assert_class(value, "data.table")
  return(value)
}

assert_args_parse_quotes <- function(quotes) {
  if (!is.null(quotes)) {
    assert_list(quotes)
  }
  return(invisible(NULL))
}

assert_return_parse_quotes <- function(value) {
  assert_class(value, "data.table")
  return(value)
}

assert_args_parse_snapshot <- function(snapshot) {
  if (!is.null(snapshot)) {
    assert_list(snapshot)
  }
  return(invisible(NULL))
}

assert_return_parse_snapshot <- function(value) {
  assert_class(value, "data.table")
  return(value)
}

assert_args_parse_news <- function(news_items) {
  if (!is.null(news_items)) {
    assert_list(news_items)
  }
  return(invisible(NULL))
}

assert_return_parse_news <- function(value) {
  assert_class(value, "data.table")
  return(value)
}

assert_args_parse_watchlist <- function(wl) {
  if (!is.null(wl)) {
    assert_list(wl)
  }
  return(invisible(NULL))
}

assert_return_parse_watchlist <- function(value) {
  assert_class(value, "data.table")
  return(value)
}

assert_args_parse_asset <- function(x) {
  if (!is.null(x)) {
    assert_list(x)
  }
  return(invisible(NULL))
}

assert_return_parse_asset <- function(value) {
  assert_class(value, "data.table")
  return(value)
}

assert_args_parse_assets <- function(items) {
  if (!is.null(items)) {
    assert_list(items)
  }
  return(invisible(NULL))
}

assert_return_parse_assets <- function(value) {
  assert_class(value, "data.table")
  return(value)
}

assert_args_parse_contract <- function(x) {
  if (!is.null(x)) {
    assert_list(x)
  }
  return(invisible(NULL))
}

assert_return_parse_contract <- function(value) {
  assert_class(value, "data.table")
  return(value)
}

assert_args_parse_contracts <- function(items) {
  if (!is.null(items)) {
    assert_list(items)
  }
  return(invisible(NULL))
}

assert_return_parse_contracts <- function(value) {
  assert_class(value, "data.table")
  return(value)
}

assert_args_parse_order <- function(x) {
  if (!is.null(x)) {
    assert_list(x)
  }
  return(invisible(NULL))
}

assert_return_parse_order <- function(value) {
  assert_class(value, "data.table")
  return(value)
}

assert_args_parse_orders <- function(items) {
  if (!is.null(items)) {
    assert_list(items)
  }
  return(invisible(NULL))
}

assert_return_parse_orders <- function(value) {
  assert_class(value, "data.table")
  return(value)
}

assert_args_alpaca_serialize_body <- function(body) {
  assert_list(body)
  return(invisible(NULL))
}

assert_return_alpaca_serialize_body <- function(value) {
  if (!is.null(value)) {
    assert_scalar_character(value)
  }
  return(value)
}

assert_args_alpaca_build_request <- function(base_url, endpoint, method, query, body, keys, .perform, .parser, is_async, timeout, simplifyVector) {
  assert_scalar_character(base_url)
  assert_scalar_character(endpoint)
  assert_scalar_character(method)
  assert_list(query)
  if (!is.null(body)) {
    assert_list(body)
  }
  if (!is.null(keys)) {
    assert_list(keys)
  }
  assert_function(.perform)
  assert_function(.parser)
  assert_scalar_logical(is_async)
  assert_scalar_double(timeout)
  assert_between(timeout, lower = 0, lower_inclusive = FALSE, upper = Inf, upper_inclusive = FALSE)
  assert_scalar_logical(simplifyVector)
  return(invisible(NULL))
}

assert_return_alpaca_build_request <- function(value) {
  return(value)
}

assert_args_alpaca_paginate <- function(base_url, endpoint, method, query, keys, .perform, .parser, is_async, items_field, max_pages, sleep, timeout) {
  assert_scalar_character(base_url)
  assert_scalar_character(endpoint)
  assert_scalar_character(method)
  assert_list(query)
  if (!is.null(keys)) {
    assert_list(keys)
  }
  assert_function(.perform)
  assert_function(.parser)
  assert_scalar_logical(is_async)
  if (!is.null(items_field)) {
    assert_scalar_character(items_field)
  }
  assert_any_of(
    max_pages,
    function(.x) {
      assert_scalar_double(.x)
      assert_between(.x, lower = 1)
    },
    function(.x) {
      assert_scalar_integer(.x)
      assert_between(.x, lower = 1)
    }
  )
  assert_scalar_double(sleep)
  assert_between(sleep, lower = 0, upper = Inf, upper_inclusive = FALSE)
  assert_scalar_double(timeout)
  assert_between(timeout, lower = 0, lower_inclusive = FALSE, upper = Inf, upper_inclusive = FALSE)
  return(invisible(NULL))
}

assert_return_alpaca_paginate <- function(value) {
  return(value)
}

assert_args_parse_alpaca_response <- function(resp, simplifyVector) {
  assert_class(resp, "httr2_response")
  assert_scalar_logical(simplifyVector)
  return(invisible(NULL))
}

assert_return_parse_alpaca_response <- function(value) {
  return(value)
}

assert_args_alpaca_fetch_bars <- function(symbol, timeframe, start, end, keys, data_base_url, .perform, is_async, adjustment, feed, limit_per_request, sleep) {
  assert_scalar_character(symbol)
  assert_scalar_character(timeframe)
  assert_any_of(
    start,
    function(.x) {
      assert_datetime(.x)
      assert_no_missing_values(.x)
    },
    function(.x) {
      assert_character(.x)
      assert_no_missing_values(.x)
    }
  )
  assert_any_of(
    end,
    function(.x) {
      assert_datetime(.x)
      assert_no_missing_values(.x)
    },
    function(.x) {
      assert_character(.x)
      assert_no_missing_values(.x)
    }
  )
  assert_list(keys)
  assert_scalar_character(data_base_url)
  assert_function(.perform)
  assert_scalar_logical(is_async)
  assert_scalar_character(adjustment)
  if (!is.null(feed)) {
    assert_scalar_character(feed)
  }
  assert_scalar_count(limit_per_request)
  assert_between(limit_per_request, lower = 1)
  assert_scalar_double(sleep)
  assert_between(sleep, lower = 0, upper = Inf, upper_inclusive = FALSE)
  return(invisible(NULL))
}

assert_return_alpaca_fetch_bars <- function(value) {
  assert_data_table(value)
  return(value)
}

assert_args_get_base_url <- function(url) {
  if (!is.null(url)) {
    assert_scalar_character(url)
  }
  return(invisible(NULL))
}

assert_return_get_base_url <- function(value) {
  assert_scalar_character(value)
  return(value)
}

assert_args_get_data_base_url <- function(url) {
  if (!is.null(url)) {
    assert_scalar_character(url)
  }
  return(invisible(NULL))
}

assert_return_get_data_base_url <- function(value) {
  assert_scalar_character(value)
  return(value)
}

assert_args_get_api_keys <- function(api_key, api_secret) {
  assert_scalar_character(api_key)
  assert_scalar_character(api_secret)
  return(invisible(NULL))
}

assert_return_get_api_keys <- function(value) {
  assert_list(value)
  assert_has_names(value, c("api_key", "api_secret"))
  assert_scalar_character(value[["api_key"]])
  assert_scalar_character(value[["api_secret"]])
  return(value)
}

assert_args_time_convert_from_alpaca <- function(x) {
  return(invisible(NULL))
}

assert_return_time_convert_from_alpaca <- function(value) {
  assert_datetime(value)
  return(value)
}

assert_args_time_convert_to_alpaca <- function(x) {
  return(invisible(NULL))
}

assert_return_time_convert_to_alpaca <- function(value) {
  assert_character(value)
  return(value)
}

