# Generated by roxyassert: do not edit by hand.
# Re-generated on devtools::document(). Commit this file like NAMESPACE.

assert_return_AlpacaAccount__get_account <- function(value) {
  assert_data_table(value)
  assert_has_columns(value, c("id", "account_number", "status", "currency", "cash", "portfolio_value", "equity", "last_equity", "buying_power", "initial_margin", "maintenance_margin", "long_market_value", "short_market_value", "pattern_day_trader", "trading_blocked", "transfers_blocked", "account_blocked", "daytrade_count", "daytrading_buying_power", "regt_buying_power", "multiplier", "sma", "created_at"))
  assert_character(value[["id"]])
  assert_no_missing_values(value[["id"]])
  assert_character(value[["account_number"]])
  assert_no_missing_values(value[["account_number"]])
  assert_character(value[["status"]])
  assert_no_missing_values(value[["status"]])
  assert_character(value[["currency"]])
  assert_no_missing_values(value[["currency"]])
  assert_character(value[["cash"]])
  assert_no_missing_values(value[["cash"]])
  assert_character(value[["portfolio_value"]])
  assert_no_missing_values(value[["portfolio_value"]])
  assert_character(value[["equity"]])
  assert_no_missing_values(value[["equity"]])
  assert_character(value[["last_equity"]])
  assert_no_missing_values(value[["last_equity"]])
  assert_character(value[["buying_power"]])
  assert_no_missing_values(value[["buying_power"]])
  assert_character(value[["initial_margin"]])
  assert_no_missing_values(value[["initial_margin"]])
  assert_character(value[["maintenance_margin"]])
  assert_no_missing_values(value[["maintenance_margin"]])
  assert_character(value[["long_market_value"]])
  assert_no_missing_values(value[["long_market_value"]])
  assert_character(value[["short_market_value"]])
  assert_no_missing_values(value[["short_market_value"]])
  assert_logical(value[["pattern_day_trader"]])
  assert_no_missing_values(value[["pattern_day_trader"]])
  assert_logical(value[["trading_blocked"]])
  assert_no_missing_values(value[["trading_blocked"]])
  assert_logical(value[["transfers_blocked"]])
  assert_no_missing_values(value[["transfers_blocked"]])
  assert_logical(value[["account_blocked"]])
  assert_no_missing_values(value[["account_blocked"]])
  assert_integer(value[["daytrade_count"]])
  assert_no_missing_values(value[["daytrade_count"]])
  assert_character(value[["daytrading_buying_power"]])
  assert_no_missing_values(value[["daytrading_buying_power"]])
  assert_character(value[["regt_buying_power"]])
  assert_no_missing_values(value[["regt_buying_power"]])
  assert_character(value[["multiplier"]])
  assert_no_missing_values(value[["multiplier"]])
  assert_character(value[["sma"]])
  assert_no_missing_values(value[["sma"]])
  assert_datetime(value[["created_at"]])
  assert_no_missing_values(value[["created_at"]])
  return(value)
}

assert_return_AlpacaAccount__get_account_config <- function(value) {
  assert_data_table(value)
  assert_has_columns(value, c("dtbp_check", "no_shorting", "suspend_trade", "trade_confirm_email", "fractional_trading", "max_margin_multiplier", "pdt_check"))
  assert_character(value[["dtbp_check"]])
  assert_no_missing_values(value[["dtbp_check"]])
  assert_logical(value[["no_shorting"]])
  assert_no_missing_values(value[["no_shorting"]])
  assert_logical(value[["suspend_trade"]])
  assert_no_missing_values(value[["suspend_trade"]])
  assert_character(value[["trade_confirm_email"]])
  assert_no_missing_values(value[["trade_confirm_email"]])
  assert_logical(value[["fractional_trading"]])
  assert_no_missing_values(value[["fractional_trading"]])
  assert_character(value[["max_margin_multiplier"]])
  assert_no_missing_values(value[["max_margin_multiplier"]])
  assert_character(value[["pdt_check"]])
  assert_no_missing_values(value[["pdt_check"]])
  return(value)
}

assert_args_AlpacaAccount__modify_account_config <- function(dtbp_check, no_shorting, suspend_trade, trade_confirm_email, fractional_trading, max_margin_multiplier, pdt_check, max_options_trading_level, ptp_no_exception_entry, disable_overnight_trading) {
  if (!is.null(dtbp_check)) {
    assert_scalar_character(dtbp_check)
  }
  if (!is.null(no_shorting)) {
    assert_scalar_logical(no_shorting)
  }
  if (!is.null(suspend_trade)) {
    assert_scalar_logical(suspend_trade)
  }
  if (!is.null(trade_confirm_email)) {
    assert_scalar_character(trade_confirm_email)
  }
  if (!is.null(fractional_trading)) {
    assert_scalar_logical(fractional_trading)
  }
  if (!is.null(max_margin_multiplier)) {
    assert_scalar_character(max_margin_multiplier)
  }
  if (!is.null(pdt_check)) {
    assert_scalar_character(pdt_check)
  }
  if (!is.null(max_options_trading_level)) {
    assert_scalar_count(max_options_trading_level)
    assert_between(max_options_trading_level, lower = 0)
  }
  if (!is.null(ptp_no_exception_entry)) {
    assert_scalar_logical(ptp_no_exception_entry)
  }
  if (!is.null(disable_overnight_trading)) {
    assert_scalar_logical(disable_overnight_trading)
  }
  return(invisible(NULL))
}

assert_return_AlpacaAccount__modify_account_config <- function(value) {
  assert_data_table(value)
  assert_has_columns(value, c("dtbp_check", "no_shorting", "suspend_trade", "trade_confirm_email", "fractional_trading", "max_margin_multiplier", "pdt_check"))
  assert_character(value[["dtbp_check"]])
  assert_no_missing_values(value[["dtbp_check"]])
  assert_logical(value[["no_shorting"]])
  assert_no_missing_values(value[["no_shorting"]])
  assert_logical(value[["suspend_trade"]])
  assert_no_missing_values(value[["suspend_trade"]])
  assert_character(value[["trade_confirm_email"]])
  assert_no_missing_values(value[["trade_confirm_email"]])
  assert_logical(value[["fractional_trading"]])
  assert_no_missing_values(value[["fractional_trading"]])
  assert_character(value[["max_margin_multiplier"]])
  assert_no_missing_values(value[["max_margin_multiplier"]])
  assert_character(value[["pdt_check"]])
  assert_no_missing_values(value[["pdt_check"]])
  return(value)
}

assert_return_AlpacaAccount__get_positions <- function(value) {
  assert_data_table(value)
  assert_has_columns(value, c("asset_id", "symbol", "exchange", "asset_class", "avg_entry_price", "qty", "side", "market_value", "cost_basis", "unrealized_pl", "unrealized_plpc", "current_price", "lastday_price", "change_today"))
  assert_character(value[["asset_id"]])
  assert_no_missing_values(value[["asset_id"]])
  assert_character(value[["symbol"]])
  assert_no_missing_values(value[["symbol"]])
  assert_character(value[["exchange"]])
  assert_no_missing_values(value[["exchange"]])
  assert_character(value[["asset_class"]])
  assert_no_missing_values(value[["asset_class"]])
  assert_character(value[["avg_entry_price"]])
  assert_no_missing_values(value[["avg_entry_price"]])
  assert_character(value[["qty"]])
  assert_no_missing_values(value[["qty"]])
  assert_character(value[["side"]])
  assert_no_missing_values(value[["side"]])
  assert_character(value[["market_value"]])
  assert_no_missing_values(value[["market_value"]])
  assert_character(value[["cost_basis"]])
  assert_no_missing_values(value[["cost_basis"]])
  assert_character(value[["unrealized_pl"]])
  assert_no_missing_values(value[["unrealized_pl"]])
  assert_character(value[["unrealized_plpc"]])
  assert_no_missing_values(value[["unrealized_plpc"]])
  assert_character(value[["current_price"]])
  assert_no_missing_values(value[["current_price"]])
  assert_character(value[["lastday_price"]])
  assert_no_missing_values(value[["lastday_price"]])
  assert_character(value[["change_today"]])
  assert_no_missing_values(value[["change_today"]])
  return(value)
}

assert_args_AlpacaAccount__get_position <- function(symbol_or_id) {
  assert_scalar_character(symbol_or_id)
  return(invisible(NULL))
}

assert_return_AlpacaAccount__get_position <- function(value) {
  assert_data_table(value)
  assert_has_columns(value, c("asset_id", "symbol", "exchange", "asset_class", "avg_entry_price", "qty", "side", "market_value", "cost_basis", "unrealized_pl", "unrealized_plpc", "current_price", "lastday_price", "change_today"))
  assert_character(value[["asset_id"]])
  assert_no_missing_values(value[["asset_id"]])
  assert_character(value[["symbol"]])
  assert_no_missing_values(value[["symbol"]])
  assert_character(value[["exchange"]])
  assert_no_missing_values(value[["exchange"]])
  assert_character(value[["asset_class"]])
  assert_no_missing_values(value[["asset_class"]])
  assert_character(value[["avg_entry_price"]])
  assert_no_missing_values(value[["avg_entry_price"]])
  assert_character(value[["qty"]])
  assert_no_missing_values(value[["qty"]])
  assert_character(value[["side"]])
  assert_no_missing_values(value[["side"]])
  assert_character(value[["market_value"]])
  assert_no_missing_values(value[["market_value"]])
  assert_character(value[["cost_basis"]])
  assert_no_missing_values(value[["cost_basis"]])
  assert_character(value[["unrealized_pl"]])
  assert_no_missing_values(value[["unrealized_pl"]])
  assert_character(value[["unrealized_plpc"]])
  assert_no_missing_values(value[["unrealized_plpc"]])
  assert_character(value[["current_price"]])
  assert_no_missing_values(value[["current_price"]])
  assert_character(value[["lastday_price"]])
  assert_no_missing_values(value[["lastday_price"]])
  assert_character(value[["change_today"]])
  assert_no_missing_values(value[["change_today"]])
  return(value)
}

assert_args_AlpacaAccount__close_position <- function(symbol_or_id, qty, percentage) {
  assert_scalar_character(symbol_or_id)
  if (!is.null(qty)) {
    assert_scalar_double(qty)
  }
  if (!is.null(percentage)) {
    assert_scalar_double(percentage)
  }
  return(invisible(NULL))
}

assert_return_AlpacaAccount__close_position <- function(value) {
  assert_data_table(value)
  assert_has_columns(value, c("id", "symbol", "side", "type", "status", "qty", "filled_qty", "created_at"))
  assert_character(value[["id"]])
  assert_no_missing_values(value[["id"]])
  assert_character(value[["symbol"]])
  assert_no_missing_values(value[["symbol"]])
  assert_character(value[["side"]])
  assert_no_missing_values(value[["side"]])
  assert_character(value[["type"]])
  assert_no_missing_values(value[["type"]])
  assert_character(value[["status"]])
  assert_no_missing_values(value[["status"]])
  assert_character(value[["qty"]])
  assert_no_missing_values(value[["qty"]])
  assert_character(value[["filled_qty"]])
  assert_no_missing_values(value[["filled_qty"]])
  assert_datetime(value[["created_at"]])
  assert_no_missing_values(value[["created_at"]])
  return(value)
}

assert_args_AlpacaAccount__close_all_positions <- function(cancel_orders) {
  assert_scalar_logical(cancel_orders)
  return(invisible(NULL))
}

assert_return_AlpacaAccount__close_all_positions <- function(value) {
  assert_data_table(value)
  return(value)
}

assert_args_AlpacaAccount__exercise_option <- function(symbol_or_id) {
  assert_scalar_character(symbol_or_id)
  return(invisible(NULL))
}

assert_return_AlpacaAccount__exercise_option <- function(value) {
  assert_data_table(value)
  assert_has_columns(value, c("symbol", "status"))
  assert_character(value[["symbol"]])
  assert_no_missing_values(value[["symbol"]])
  assert_character(value[["status"]])
  assert_no_missing_values(value[["status"]])
  return(value)
}

assert_args_AlpacaAccount__get_portfolio_history <- function(period, timeframe, start, end, intraday_reporting, pnl_reset, date_start, date_end) {
  if (!is.null(period)) {
    assert_scalar_character(period)
  }
  if (!is.null(timeframe)) {
    assert_scalar_character(timeframe)
  }
  if (!is.null(start)) {
    assert_scalar_character(start)
  }
  if (!is.null(end)) {
    assert_scalar_character(end)
  }
  if (!is.null(intraday_reporting)) {
    assert_scalar_character(intraday_reporting)
  }
  if (!is.null(pnl_reset)) {
    assert_scalar_character(pnl_reset)
  }
  if (!is.null(date_start)) {
    assert_scalar_character(date_start)
  }
  if (!is.null(date_end)) {
    assert_scalar_character(date_end)
  }
  return(invisible(NULL))
}

assert_return_AlpacaAccount__get_portfolio_history <- function(value) {
  assert_data_table(value)
  assert_has_columns(value, c("timestamp", "equity", "profit_loss", "profit_loss_pct"))
  assert_datetime(value[["timestamp"]])
  assert_no_missing_values(value[["timestamp"]])
  assert_double(value[["equity"]])
  assert_double(value[["profit_loss"]])
  assert_double(value[["profit_loss_pct"]])
  return(value)
}

assert_args_AlpacaAccount__get_activities <- function(activity_types, category, date, until, after, direction, page_token) {
  if (!is.null(activity_types)) {
    assert_scalar_character(activity_types)
  }
  if (!is.null(category)) {
    assert_scalar_character(category)
  }
  if (!is.null(date)) {
    assert_scalar_character(date)
  }
  if (!is.null(until)) {
    assert_scalar_character(until)
  }
  if (!is.null(after)) {
    assert_scalar_character(after)
  }
  if (!is.null(direction)) {
    assert_scalar_character(direction)
  }
  if (!is.null(page_token)) {
    assert_scalar_character(page_token)
  }
  return(invisible(NULL))
}

assert_return_AlpacaAccount__get_activities <- function(value) {
  assert_data_table(value)
  assert_has_columns(value, c("id", "activity_type", "symbol", "side", "qty", "price", "transaction_time"))
  assert_character(value[["id"]])
  assert_no_missing_values(value[["id"]])
  assert_character(value[["activity_type"]])
  assert_no_missing_values(value[["activity_type"]])
  assert_character(value[["symbol"]])
  assert_character(value[["side"]])
  assert_character(value[["qty"]])
  assert_character(value[["price"]])
  assert_datetime(value[["transaction_time"]])
  return(value)
}

assert_args_AlpacaAccount__get_activities_by_type <- function(activity_type, date, until, after, direction, page_token) {
  assert_scalar_character(activity_type)
  if (!is.null(date)) {
    assert_scalar_character(date)
  }
  if (!is.null(until)) {
    assert_scalar_character(until)
  }
  if (!is.null(after)) {
    assert_scalar_character(after)
  }
  if (!is.null(direction)) {
    assert_scalar_character(direction)
  }
  if (!is.null(page_token)) {
    assert_scalar_character(page_token)
  }
  return(invisible(NULL))
}

assert_return_AlpacaAccount__get_activities_by_type <- function(value) {
  assert_data_table(value)
  assert_has_columns(value, c("id", "activity_type", "symbol", "side", "qty", "price", "transaction_time"))
  assert_character(value[["id"]])
  assert_no_missing_values(value[["id"]])
  assert_character(value[["activity_type"]])
  assert_no_missing_values(value[["activity_type"]])
  assert_character(value[["symbol"]])
  assert_character(value[["side"]])
  assert_character(value[["qty"]])
  assert_character(value[["price"]])
  assert_datetime(value[["transaction_time"]])
  return(value)
}

assert_return_AlpacaAccount__get_watchlists <- function(value) {
  assert_data_table(value)
  assert_has_columns(value, c("id", "account_id", "name", "created_at", "updated_at"))
  assert_character(value[["id"]])
  assert_no_missing_values(value[["id"]])
  assert_character(value[["account_id"]])
  assert_no_missing_values(value[["account_id"]])
  assert_character(value[["name"]])
  assert_no_missing_values(value[["name"]])
  assert_datetime(value[["created_at"]])
  assert_no_missing_values(value[["created_at"]])
  assert_datetime(value[["updated_at"]])
  assert_no_missing_values(value[["updated_at"]])
  return(value)
}

assert_args_AlpacaAccount__get_watchlist <- function(watchlist_id) {
  assert_scalar_character(watchlist_id)
  return(invisible(NULL))
}

assert_return_AlpacaAccount__get_watchlist <- function(value) {
  assert_data_table(value)
  assert_has_columns(value, c("id", "account_id", "name", "created_at", "updated_at", "asset_id", "asset_symbol", "asset_name", "asset_attributes"))
  assert_character(value[["id"]])
  assert_no_missing_values(value[["id"]])
  assert_character(value[["account_id"]])
  assert_no_missing_values(value[["account_id"]])
  assert_character(value[["name"]])
  assert_no_missing_values(value[["name"]])
  assert_datetime(value[["created_at"]])
  assert_no_missing_values(value[["created_at"]])
  assert_datetime(value[["updated_at"]])
  assert_no_missing_values(value[["updated_at"]])
  assert_character(value[["asset_id"]])
  assert_character(value[["asset_symbol"]])
  assert_character(value[["asset_name"]])
  assert_character(value[["asset_attributes"]])
  return(value)
}

assert_args_AlpacaAccount__add_watchlist <- function(name, symbols) {
  assert_scalar_character(name)
  if (!is.null(symbols)) {
    assert_character(symbols)
    assert_no_missing_values(symbols)
  }
  return(invisible(NULL))
}

assert_return_AlpacaAccount__add_watchlist <- function(value) {
  assert_data_table(value)
  assert_has_columns(value, c("id", "account_id", "name", "created_at", "updated_at", "asset_id", "asset_symbol", "asset_name", "asset_attributes"))
  assert_character(value[["id"]])
  assert_no_missing_values(value[["id"]])
  assert_character(value[["account_id"]])
  assert_no_missing_values(value[["account_id"]])
  assert_character(value[["name"]])
  assert_no_missing_values(value[["name"]])
  assert_datetime(value[["created_at"]])
  assert_no_missing_values(value[["created_at"]])
  assert_datetime(value[["updated_at"]])
  assert_no_missing_values(value[["updated_at"]])
  assert_character(value[["asset_id"]])
  assert_character(value[["asset_symbol"]])
  assert_character(value[["asset_name"]])
  assert_character(value[["asset_attributes"]])
  return(value)
}

assert_args_AlpacaAccount__modify_watchlist <- function(watchlist_id, name, symbols) {
  assert_scalar_character(watchlist_id)
  assert_scalar_character(name)
  assert_character(symbols)
  assert_no_missing_values(symbols)
  return(invisible(NULL))
}

assert_return_AlpacaAccount__modify_watchlist <- function(value) {
  assert_data_table(value)
  assert_has_columns(value, c("id", "account_id", "name", "created_at", "updated_at", "asset_id", "asset_symbol", "asset_name", "asset_attributes"))
  assert_character(value[["id"]])
  assert_no_missing_values(value[["id"]])
  assert_character(value[["account_id"]])
  assert_no_missing_values(value[["account_id"]])
  assert_character(value[["name"]])
  assert_no_missing_values(value[["name"]])
  assert_datetime(value[["created_at"]])
  assert_no_missing_values(value[["created_at"]])
  assert_datetime(value[["updated_at"]])
  assert_no_missing_values(value[["updated_at"]])
  assert_character(value[["asset_id"]])
  assert_character(value[["asset_symbol"]])
  assert_character(value[["asset_name"]])
  assert_character(value[["asset_attributes"]])
  return(value)
}

assert_args_AlpacaAccount__add_watchlist_symbol <- function(watchlist_id, symbol) {
  assert_scalar_character(watchlist_id)
  assert_scalar_character(symbol)
  return(invisible(NULL))
}

assert_return_AlpacaAccount__add_watchlist_symbol <- function(value) {
  assert_data_table(value)
  assert_has_columns(value, c("id", "account_id", "name", "created_at", "updated_at", "asset_id", "asset_symbol", "asset_name", "asset_attributes"))
  assert_character(value[["id"]])
  assert_no_missing_values(value[["id"]])
  assert_character(value[["account_id"]])
  assert_no_missing_values(value[["account_id"]])
  assert_character(value[["name"]])
  assert_no_missing_values(value[["name"]])
  assert_datetime(value[["created_at"]])
  assert_no_missing_values(value[["created_at"]])
  assert_datetime(value[["updated_at"]])
  assert_no_missing_values(value[["updated_at"]])
  assert_character(value[["asset_id"]])
  assert_character(value[["asset_symbol"]])
  assert_character(value[["asset_name"]])
  assert_character(value[["asset_attributes"]])
  return(value)
}

assert_args_AlpacaAccount__cancel_watchlist_symbol <- function(watchlist_id, symbol) {
  assert_scalar_character(watchlist_id)
  assert_scalar_character(symbol)
  return(invisible(NULL))
}

assert_return_AlpacaAccount__cancel_watchlist_symbol <- function(value) {
  assert_data_table(value)
  return(value)
}

assert_args_AlpacaAccount__cancel_watchlist <- function(watchlist_id) {
  assert_scalar_character(watchlist_id)
  return(invisible(NULL))
}

assert_return_AlpacaAccount__cancel_watchlist <- function(value) {
  assert_data_table(value)
  assert_has_columns(value, c("watchlist_id", "status"))
  assert_character(value[["watchlist_id"]])
  assert_no_missing_values(value[["watchlist_id"]])
  assert_character(value[["status"]])
  assert_no_missing_values(value[["status"]])
  return(value)
}

assert_args_AlpacaBase__initialize <- function(keys, base_url, async) {
  assert_list(keys)
  assert_scalar_character(base_url)
  assert_scalar_logical(async)
  return(invisible(NULL))
}

assert_return_AlpacaBase__initialize <- function(value) {
  assert_class(value, "AlpacaBase")
  return(value)
}

assert_args_AlpacaMarketData__initialize <- function(keys, base_url, data_base_url, async) {
  assert_list(keys)
  assert_scalar_character(base_url)
  assert_scalar_character(data_base_url)
  assert_scalar_logical(async)
  return(invisible(NULL))
}

assert_return_AlpacaMarketData__initialize <- function(value) {
  assert_class(value, "AlpacaMarketData")
  return(value)
}

assert_args_AlpacaMarketData__get_bars <- function(symbol, timeframe, start, end, limit, adjustment, asof, feed, currency, sort, page_token, max_pages, sleep) {
  assert_scalar_character(symbol)
  assert_scalar_character(timeframe)
  if (!is.null(start)) {
    assert_scalar_character(start)
  }
  if (!is.null(end)) {
    assert_scalar_character(end)
  }
  if (!is.null(limit)) {
    assert_scalar_count(limit)
    assert_between(limit, lower = 1, upper = 10001, upper_inclusive = FALSE)
  }
  if (!is.null(adjustment)) {
    assert_scalar_character(adjustment)
  }
  if (!is.null(asof)) {
    assert_scalar_character(asof)
  }
  if (!is.null(feed)) {
    assert_scalar_character(feed)
  }
  if (!is.null(currency)) {
    assert_scalar_character(currency)
  }
  if (!is.null(sort)) {
    assert_scalar_character(sort)
  }
  if (!is.null(page_token)) {
    assert_scalar_character(page_token)
  }
  assert_any_of(
    max_pages,
    function(.x) {
      assert_scalar_double(.x)
      assert_between(.x, lower = 1)
    },
    function(.x) {
      assert_scalar_integer(.x)
      assert_between(.x, lower = 1)
    }
  )
  assert_scalar_double(sleep)
  assert_between(sleep, lower = 0, upper = Inf, upper_inclusive = FALSE)
  return(invisible(NULL))
}

assert_return_AlpacaMarketData__get_bars <- function(value) {
  assert_data_table(value)
  assert_has_columns(value, c("timestamp", "open", "high", "low", "close", "volume", "trade_count", "vwap"))
  assert_datetime(value[["timestamp"]])
  assert_no_missing_values(value[["timestamp"]])
  assert_double(value[["open"]])
  assert_no_missing_values(value[["open"]])
  assert_double(value[["high"]])
  assert_no_missing_values(value[["high"]])
  assert_double(value[["low"]])
  assert_no_missing_values(value[["low"]])
  assert_double(value[["close"]])
  assert_no_missing_values(value[["close"]])
  assert_double(value[["volume"]])
  assert_no_missing_values(value[["volume"]])
  assert_double(value[["trade_count"]])
  assert_no_missing_values(value[["trade_count"]])
  assert_double(value[["vwap"]])
  assert_no_missing_values(value[["vwap"]])
  return(value)
}

assert_args_AlpacaMarketData__get_bars_multi <- function(symbols, timeframe, start, end, limit, adjustment, asof, feed, currency, sort, page_token, max_pages, sleep) {
  assert_character(symbols)
  assert_no_missing_values(symbols)
  assert_scalar_character(timeframe)
  if (!is.null(start)) {
    assert_scalar_character(start)
  }
  if (!is.null(end)) {
    assert_scalar_character(end)
  }
  if (!is.null(limit)) {
    assert_scalar_count(limit)
    assert_between(limit, lower = 1, upper = 10001, upper_inclusive = FALSE)
  }
  if (!is.null(adjustment)) {
    assert_scalar_character(adjustment)
  }
  if (!is.null(asof)) {
    assert_scalar_character(asof)
  }
  if (!is.null(feed)) {
    assert_scalar_character(feed)
  }
  if (!is.null(currency)) {
    assert_scalar_character(currency)
  }
  if (!is.null(sort)) {
    assert_scalar_character(sort)
  }
  if (!is.null(page_token)) {
    assert_scalar_character(page_token)
  }
  assert_any_of(
    max_pages,
    function(.x) {
      assert_scalar_double(.x)
      assert_between(.x, lower = 1)
    },
    function(.x) {
      assert_scalar_integer(.x)
      assert_between(.x, lower = 1)
    }
  )
  assert_scalar_double(sleep)
  assert_between(sleep, lower = 0, upper = Inf, upper_inclusive = FALSE)
  return(invisible(NULL))
}

assert_return_AlpacaMarketData__get_bars_multi <- function(value) {
  assert_data_table(value)
  assert_has_columns(value, c("timestamp", "open", "high", "low", "close", "volume", "trade_count", "vwap", "symbol"))
  assert_datetime(value[["timestamp"]])
  assert_no_missing_values(value[["timestamp"]])
  assert_double(value[["open"]])
  assert_no_missing_values(value[["open"]])
  assert_double(value[["high"]])
  assert_no_missing_values(value[["high"]])
  assert_double(value[["low"]])
  assert_no_missing_values(value[["low"]])
  assert_double(value[["close"]])
  assert_no_missing_values(value[["close"]])
  assert_double(value[["volume"]])
  assert_no_missing_values(value[["volume"]])
  assert_double(value[["trade_count"]])
  assert_no_missing_values(value[["trade_count"]])
  assert_double(value[["vwap"]])
  assert_no_missing_values(value[["vwap"]])
  assert_character(value[["symbol"]])
  assert_no_missing_values(value[["symbol"]])
  return(value)
}

assert_args_AlpacaMarketData__get_latest_bar <- function(symbol, feed) {
  assert_scalar_character(symbol)
  if (!is.null(feed)) {
    assert_scalar_character(feed)
  }
  return(invisible(NULL))
}

assert_return_AlpacaMarketData__get_latest_bar <- function(value) {
  assert_data_table(value)
  assert_has_columns(value, c("timestamp", "open", "high", "low", "close", "volume", "trade_count", "vwap"))
  assert_datetime(value[["timestamp"]])
  assert_no_missing_values(value[["timestamp"]])
  assert_double(value[["open"]])
  assert_no_missing_values(value[["open"]])
  assert_double(value[["high"]])
  assert_no_missing_values(value[["high"]])
  assert_double(value[["low"]])
  assert_no_missing_values(value[["low"]])
  assert_double(value[["close"]])
  assert_no_missing_values(value[["close"]])
  assert_double(value[["volume"]])
  assert_no_missing_values(value[["volume"]])
  assert_double(value[["trade_count"]])
  assert_no_missing_values(value[["trade_count"]])
  assert_double(value[["vwap"]])
  assert_no_missing_values(value[["vwap"]])
  return(value)
}

assert_args_AlpacaMarketData__get_latest_trade <- function(symbol, feed, currency) {
  assert_scalar_character(symbol)
  if (!is.null(feed)) {
    assert_scalar_character(feed)
  }
  if (!is.null(currency)) {
    assert_scalar_character(currency)
  }
  return(invisible(NULL))
}

assert_return_AlpacaMarketData__get_latest_trade <- function(value) {
  assert_data_table(value)
  assert_has_columns(value, c("timestamp", "price", "size", "exchange", "tape", "id", "conditions"))
  assert_datetime(value[["timestamp"]])
  assert_no_missing_values(value[["timestamp"]])
  assert_double(value[["price"]])
  assert_no_missing_values(value[["price"]])
  assert_integer(value[["size"]])
  assert_no_missing_values(value[["size"]])
  assert_character(value[["exchange"]])
  assert_no_missing_values(value[["exchange"]])
  assert_character(value[["tape"]])
  assert_no_missing_values(value[["tape"]])
  assert_double(value[["id"]])
  assert_no_missing_values(value[["id"]])
  assert_character(value[["conditions"]])
  return(value)
}

assert_args_AlpacaMarketData__get_latest_quote <- function(symbol, feed, currency) {
  assert_scalar_character(symbol)
  if (!is.null(feed)) {
    assert_scalar_character(feed)
  }
  if (!is.null(currency)) {
    assert_scalar_character(currency)
  }
  return(invisible(NULL))
}

assert_return_AlpacaMarketData__get_latest_quote <- function(value) {
  assert_data_table(value)
  assert_has_columns(value, c("timestamp", "ask_exchange", "ask_price", "ask_size", "bid_exchange", "bid_price", "bid_size", "tape", "conditions"))
  assert_datetime(value[["timestamp"]])
  assert_no_missing_values(value[["timestamp"]])
  assert_character(value[["ask_exchange"]])
  assert_no_missing_values(value[["ask_exchange"]])
  assert_double(value[["ask_price"]])
  assert_integer(value[["ask_size"]])
  assert_no_missing_values(value[["ask_size"]])
  assert_character(value[["bid_exchange"]])
  assert_no_missing_values(value[["bid_exchange"]])
  assert_double(value[["bid_price"]])
  assert_integer(value[["bid_size"]])
  assert_no_missing_values(value[["bid_size"]])
  assert_character(value[["tape"]])
  assert_no_missing_values(value[["tape"]])
  assert_character(value[["conditions"]])
  return(value)
}

assert_args_AlpacaMarketData__get_snapshot <- function(symbol, feed, currency) {
  assert_scalar_character(symbol)
  if (!is.null(feed)) {
    assert_scalar_character(feed)
  }
  if (!is.null(currency)) {
    assert_scalar_character(currency)
  }
  return(invisible(NULL))
}

assert_return_AlpacaMarketData__get_snapshot <- function(value) {
  assert_data_table(value)
  assert_has_columns(value, c("latest_trade_timestamp", "latest_trade_price", "latest_trade_size", "latest_trade_conditions", "latest_quote_timestamp", "latest_quote_ask_price", "latest_quote_bid_price", "latest_quote_ask_size", "latest_quote_bid_size", "latest_quote_conditions"))
  assert_datetime(value[["latest_trade_timestamp"]])
  assert_double(value[["latest_trade_price"]])
  assert_integer(value[["latest_trade_size"]])
  assert_character(value[["latest_trade_conditions"]])
  assert_datetime(value[["latest_quote_timestamp"]])
  assert_no_missing_values(value[["latest_quote_timestamp"]])
  assert_double(value[["latest_quote_ask_price"]])
  assert_double(value[["latest_quote_bid_price"]])
  assert_integer(value[["latest_quote_ask_size"]])
  assert_no_missing_values(value[["latest_quote_ask_size"]])
  assert_integer(value[["latest_quote_bid_size"]])
  assert_no_missing_values(value[["latest_quote_bid_size"]])
  assert_character(value[["latest_quote_conditions"]])
  return(value)
}

assert_args_AlpacaMarketData__get_latest_bars_multi <- function(symbols, feed, currency) {
  assert_character(symbols)
  assert_no_missing_values(symbols)
  if (!is.null(feed)) {
    assert_scalar_character(feed)
  }
  if (!is.null(currency)) {
    assert_scalar_character(currency)
  }
  return(invisible(NULL))
}

assert_return_AlpacaMarketData__get_latest_bars_multi <- function(value) {
  assert_data_table(value)
  assert_has_columns(value, c("timestamp", "open", "high", "low", "close", "volume", "trade_count", "vwap", "symbol"))
  assert_datetime(value[["timestamp"]])
  assert_no_missing_values(value[["timestamp"]])
  assert_double(value[["open"]])
  assert_no_missing_values(value[["open"]])
  assert_double(value[["high"]])
  assert_no_missing_values(value[["high"]])
  assert_double(value[["low"]])
  assert_no_missing_values(value[["low"]])
  assert_double(value[["close"]])
  assert_no_missing_values(value[["close"]])
  assert_double(value[["volume"]])
  assert_no_missing_values(value[["volume"]])
  assert_double(value[["trade_count"]])
  assert_no_missing_values(value[["trade_count"]])
  assert_double(value[["vwap"]])
  assert_no_missing_values(value[["vwap"]])
  assert_character(value[["symbol"]])
  assert_no_missing_values(value[["symbol"]])
  return(value)
}

assert_args_AlpacaMarketData__get_latest_trades_multi <- function(symbols, feed, currency) {
  assert_character(symbols)
  assert_no_missing_values(symbols)
  if (!is.null(feed)) {
    assert_scalar_character(feed)
  }
  if (!is.null(currency)) {
    assert_scalar_character(currency)
  }
  return(invisible(NULL))
}

assert_return_AlpacaMarketData__get_latest_trades_multi <- function(value) {
  assert_data_table(value)
  assert_has_columns(value, c("timestamp", "price", "size", "exchange", "tape", "id", "conditions", "symbol"))
  assert_datetime(value[["timestamp"]])
  assert_no_missing_values(value[["timestamp"]])
  assert_double(value[["price"]])
  assert_no_missing_values(value[["price"]])
  assert_integer(value[["size"]])
  assert_no_missing_values(value[["size"]])
  assert_character(value[["exchange"]])
  assert_no_missing_values(value[["exchange"]])
  assert_character(value[["tape"]])
  assert_no_missing_values(value[["tape"]])
  assert_double(value[["id"]])
  assert_no_missing_values(value[["id"]])
  assert_character(value[["conditions"]])
  assert_character(value[["symbol"]])
  assert_no_missing_values(value[["symbol"]])
  return(value)
}

assert_args_AlpacaMarketData__get_latest_quotes_multi <- function(symbols, feed, currency) {
  assert_character(symbols)
  assert_no_missing_values(symbols)
  if (!is.null(feed)) {
    assert_scalar_character(feed)
  }
  if (!is.null(currency)) {
    assert_scalar_character(currency)
  }
  return(invisible(NULL))
}

assert_return_AlpacaMarketData__get_latest_quotes_multi <- function(value) {
  assert_data_table(value)
  assert_has_columns(value, c("timestamp", "ask_exchange", "ask_price", "ask_size", "bid_exchange", "bid_price", "bid_size", "tape", "conditions", "symbol"))
  assert_datetime(value[["timestamp"]])
  assert_no_missing_values(value[["timestamp"]])
  assert_character(value[["ask_exchange"]])
  assert_no_missing_values(value[["ask_exchange"]])
  assert_double(value[["ask_price"]])
  assert_integer(value[["ask_size"]])
  assert_no_missing_values(value[["ask_size"]])
  assert_character(value[["bid_exchange"]])
  assert_no_missing_values(value[["bid_exchange"]])
  assert_double(value[["bid_price"]])
  assert_integer(value[["bid_size"]])
  assert_no_missing_values(value[["bid_size"]])
  assert_character(value[["tape"]])
  assert_no_missing_values(value[["tape"]])
  assert_character(value[["conditions"]])
  assert_character(value[["symbol"]])
  assert_no_missing_values(value[["symbol"]])
  return(value)
}

assert_args_AlpacaMarketData__get_snapshots_multi <- function(symbols, feed, currency) {
  assert_character(symbols)
  assert_no_missing_values(symbols)
  if (!is.null(feed)) {
    assert_scalar_character(feed)
  }
  if (!is.null(currency)) {
    assert_scalar_character(currency)
  }
  return(invisible(NULL))
}

assert_return_AlpacaMarketData__get_snapshots_multi <- function(value) {
  assert_data_table(value)
  assert_has_columns(value, c("latest_trade_timestamp", "latest_trade_price", "latest_trade_size", "latest_trade_conditions", "latest_quote_timestamp", "latest_quote_ask_price", "latest_quote_bid_price", "latest_quote_ask_size", "latest_quote_bid_size", "latest_quote_conditions", "symbol"))
  assert_datetime(value[["latest_trade_timestamp"]])
  assert_double(value[["latest_trade_price"]])
  assert_integer(value[["latest_trade_size"]])
  assert_character(value[["latest_trade_conditions"]])
  assert_datetime(value[["latest_quote_timestamp"]])
  assert_no_missing_values(value[["latest_quote_timestamp"]])
  assert_double(value[["latest_quote_ask_price"]])
  assert_double(value[["latest_quote_bid_price"]])
  assert_integer(value[["latest_quote_ask_size"]])
  assert_no_missing_values(value[["latest_quote_ask_size"]])
  assert_integer(value[["latest_quote_bid_size"]])
  assert_no_missing_values(value[["latest_quote_bid_size"]])
  assert_character(value[["latest_quote_conditions"]])
  assert_character(value[["symbol"]])
  assert_no_missing_values(value[["symbol"]])
  return(value)
}

assert_args_AlpacaMarketData__get_trades <- function(symbol, start, end, limit, asof, feed, currency, sort, page_token) {
  assert_scalar_character(symbol)
  if (!is.null(start)) {
    assert_scalar_character(start)
  }
  if (!is.null(end)) {
    assert_scalar_character(end)
  }
  if (!is.null(limit)) {
    assert_scalar_count(limit)
    assert_between(limit, lower = 1, upper = 10001, upper_inclusive = FALSE)
  }
  if (!is.null(asof)) {
    assert_scalar_character(asof)
  }
  if (!is.null(feed)) {
    assert_scalar_character(feed)
  }
  if (!is.null(currency)) {
    assert_scalar_character(currency)
  }
  if (!is.null(sort)) {
    assert_scalar_character(sort)
  }
  if (!is.null(page_token)) {
    assert_scalar_character(page_token)
  }
  return(invisible(NULL))
}

assert_return_AlpacaMarketData__get_trades <- function(value) {
  assert_data_table(value)
  assert_has_columns(value, c("timestamp", "price", "size", "exchange", "tape", "id", "conditions"))
  assert_datetime(value[["timestamp"]])
  assert_no_missing_values(value[["timestamp"]])
  assert_double(value[["price"]])
  assert_no_missing_values(value[["price"]])
  assert_integer(value[["size"]])
  assert_no_missing_values(value[["size"]])
  assert_character(value[["exchange"]])
  assert_no_missing_values(value[["exchange"]])
  assert_character(value[["tape"]])
  assert_no_missing_values(value[["tape"]])
  assert_double(value[["id"]])
  assert_no_missing_values(value[["id"]])
  assert_character(value[["conditions"]])
  return(value)
}

assert_args_AlpacaMarketData__get_quotes <- function(symbol, start, end, limit, asof, feed, currency, sort, page_token) {
  assert_scalar_character(symbol)
  if (!is.null(start)) {
    assert_scalar_character(start)
  }
  if (!is.null(end)) {
    assert_scalar_character(end)
  }
  if (!is.null(limit)) {
    assert_scalar_count(limit)
    assert_between(limit, lower = 1, upper = 10001, upper_inclusive = FALSE)
  }
  if (!is.null(asof)) {
    assert_scalar_character(asof)
  }
  if (!is.null(feed)) {
    assert_scalar_character(feed)
  }
  if (!is.null(currency)) {
    assert_scalar_character(currency)
  }
  if (!is.null(sort)) {
    assert_scalar_character(sort)
  }
  if (!is.null(page_token)) {
    assert_scalar_character(page_token)
  }
  return(invisible(NULL))
}

assert_return_AlpacaMarketData__get_quotes <- function(value) {
  assert_data_table(value)
  assert_has_columns(value, c("timestamp", "ask_exchange", "ask_price", "ask_size", "bid_exchange", "bid_price", "bid_size", "tape", "conditions"))
  assert_datetime(value[["timestamp"]])
  assert_no_missing_values(value[["timestamp"]])
  assert_character(value[["ask_exchange"]])
  assert_no_missing_values(value[["ask_exchange"]])
  assert_double(value[["ask_price"]])
  assert_integer(value[["ask_size"]])
  assert_no_missing_values(value[["ask_size"]])
  assert_character(value[["bid_exchange"]])
  assert_no_missing_values(value[["bid_exchange"]])
  assert_double(value[["bid_price"]])
  assert_integer(value[["bid_size"]])
  assert_no_missing_values(value[["bid_size"]])
  assert_character(value[["tape"]])
  assert_no_missing_values(value[["tape"]])
  assert_character(value[["conditions"]])
  return(value)
}

assert_args_AlpacaMarketData__get_assets <- function(status, asset_class, exchange, attributes) {
  if (!is.null(status)) {
    assert_scalar_character(status)
  }
  if (!is.null(asset_class)) {
    assert_scalar_character(asset_class)
  }
  if (!is.null(exchange)) {
    assert_scalar_character(exchange)
  }
  if (!is.null(attributes)) {
    assert_scalar_character(attributes)
  }
  return(invisible(NULL))
}

assert_return_AlpacaMarketData__get_assets <- function(value) {
  assert_data_table(value)
  assert_has_columns(value, c("id", "class", "exchange", "symbol", "name", "status", "tradable", "marginable", "shortable", "fractionable", "attributes"))
  assert_character(value[["id"]])
  assert_no_missing_values(value[["id"]])
  assert_character(value[["class"]])
  assert_no_missing_values(value[["class"]])
  assert_character(value[["exchange"]])
  assert_no_missing_values(value[["exchange"]])
  assert_character(value[["symbol"]])
  assert_no_missing_values(value[["symbol"]])
  assert_character(value[["name"]])
  assert_no_missing_values(value[["name"]])
  assert_character(value[["status"]])
  assert_no_missing_values(value[["status"]])
  assert_logical(value[["tradable"]])
  assert_no_missing_values(value[["tradable"]])
  assert_logical(value[["marginable"]])
  assert_no_missing_values(value[["marginable"]])
  assert_logical(value[["shortable"]])
  assert_no_missing_values(value[["shortable"]])
  assert_logical(value[["fractionable"]])
  assert_no_missing_values(value[["fractionable"]])
  assert_character(value[["attributes"]])
  return(value)
}

assert_args_AlpacaMarketData__get_asset <- function(symbol_or_id) {
  assert_scalar_character(symbol_or_id)
  return(invisible(NULL))
}

assert_return_AlpacaMarketData__get_asset <- function(value) {
  assert_data_table(value)
  assert_has_columns(value, c("id", "class", "exchange", "symbol", "name", "status", "tradable", "marginable", "shortable", "fractionable", "attributes"))
  assert_character(value[["id"]])
  assert_no_missing_values(value[["id"]])
  assert_character(value[["class"]])
  assert_no_missing_values(value[["class"]])
  assert_character(value[["exchange"]])
  assert_no_missing_values(value[["exchange"]])
  assert_character(value[["symbol"]])
  assert_no_missing_values(value[["symbol"]])
  assert_character(value[["name"]])
  assert_no_missing_values(value[["name"]])
  assert_character(value[["status"]])
  assert_no_missing_values(value[["status"]])
  assert_logical(value[["tradable"]])
  assert_no_missing_values(value[["tradable"]])
  assert_logical(value[["marginable"]])
  assert_no_missing_values(value[["marginable"]])
  assert_logical(value[["shortable"]])
  assert_no_missing_values(value[["shortable"]])
  assert_logical(value[["fractionable"]])
  assert_no_missing_values(value[["fractionable"]])
  assert_character(value[["attributes"]])
  return(value)
}

assert_args_AlpacaMarketData__get_calendar <- function(start, end, date_type) {
  if (!is.null(start)) {
    assert_scalar_character(start)
  }
  if (!is.null(end)) {
    assert_scalar_character(end)
  }
  if (!is.null(date_type)) {
    assert_scalar_character(date_type)
  }
  return(invisible(NULL))
}

assert_return_AlpacaMarketData__get_calendar <- function(value) {
  assert_data_table(value)
  assert_has_columns(value, c("date", "open", "close", "session_open", "session_close", "settlement_date"))
  assert_date(value[["date"]])
  assert_no_missing_values(value[["date"]])
  assert_datetime(value[["open"]])
  assert_no_missing_values(value[["open"]])
  assert_datetime(value[["close"]])
  assert_no_missing_values(value[["close"]])
  assert_datetime(value[["session_open"]])
  assert_no_missing_values(value[["session_open"]])
  assert_datetime(value[["session_close"]])
  assert_no_missing_values(value[["session_close"]])
  assert_date(value[["settlement_date"]])
  assert_no_missing_values(value[["settlement_date"]])
  return(value)
}

assert_return_AlpacaMarketData__get_clock <- function(value) {
  assert_data_table(value)
  assert_has_columns(value, c("timestamp", "is_open", "next_open", "next_close"))
  assert_datetime(value[["timestamp"]])
  assert_no_missing_values(value[["timestamp"]])
  assert_logical(value[["is_open"]])
  assert_no_missing_values(value[["is_open"]])
  assert_datetime(value[["next_open"]])
  assert_no_missing_values(value[["next_open"]])
  assert_datetime(value[["next_close"]])
  assert_no_missing_values(value[["next_close"]])
  return(value)
}

assert_args_AlpacaMarketData__get_corporate_actions <- function(ca_types, since, until, symbol, cusip, date_type) {
  assert_scalar_character(ca_types)
  assert_scalar_character(since)
  assert_scalar_character(until)
  if (!is.null(symbol)) {
    assert_scalar_character(symbol)
  }
  if (!is.null(cusip)) {
    assert_scalar_character(cusip)
  }
  if (!is.null(date_type)) {
    assert_scalar_character(date_type)
  }
  return(invisible(NULL))
}

assert_return_AlpacaMarketData__get_corporate_actions <- function(value) {
  assert_data_table(value)
  assert_has_columns(value, c("id", "corporate_action_id", "ca_type", "ca_sub_type", "initiating_symbol", "target_symbol", "declaration_date", "ex_date", "record_date", "payable_date", "cash", "old_rate", "new_rate"))
  assert_character(value[["id"]])
  assert_no_missing_values(value[["id"]])
  assert_character(value[["corporate_action_id"]])
  assert_no_missing_values(value[["corporate_action_id"]])
  assert_character(value[["ca_type"]])
  assert_no_missing_values(value[["ca_type"]])
  assert_character(value[["ca_sub_type"]])
  assert_no_missing_values(value[["ca_sub_type"]])
  assert_character(value[["initiating_symbol"]])
  assert_no_missing_values(value[["initiating_symbol"]])
  assert_character(value[["target_symbol"]])
  assert_no_missing_values(value[["target_symbol"]])
  assert_date(value[["declaration_date"]])
  assert_no_missing_values(value[["declaration_date"]])
  assert_date(value[["ex_date"]])
  assert_no_missing_values(value[["ex_date"]])
  assert_date(value[["record_date"]])
  assert_no_missing_values(value[["record_date"]])
  assert_date(value[["payable_date"]])
  assert_no_missing_values(value[["payable_date"]])
  assert_character(value[["cash"]])
  assert_character(value[["old_rate"]])
  assert_character(value[["new_rate"]])
  return(value)
}

assert_args_AlpacaMarketData__get_news <- function(symbols, start, end, limit, sort, include_content, exclude_contentless, page_token) {
  if (!is.null(symbols)) {
    assert_character(symbols)
    assert_no_missing_values(symbols)
  }
  if (!is.null(start)) {
    assert_scalar_character(start)
  }
  if (!is.null(end)) {
    assert_scalar_character(end)
  }
  if (!is.null(limit)) {
    assert_scalar_count(limit)
    assert_between(limit, lower = 1)
  }
  if (!is.null(sort)) {
    assert_scalar_character(sort)
  }
  if (!is.null(include_content)) {
    assert_scalar_logical(include_content)
  }
  if (!is.null(exclude_contentless)) {
    assert_scalar_logical(exclude_contentless)
  }
  if (!is.null(page_token)) {
    assert_scalar_character(page_token)
  }
  return(invisible(NULL))
}

assert_return_AlpacaMarketData__get_news <- function(value) {
  assert_data_table(value)
  assert_has_columns(value, c("id", "headline", "author", "source", "summary", "url", "symbols", "created_at", "updated_at", "image_sizes", "image_urls"))
  assert_double(value[["id"]])
  assert_no_missing_values(value[["id"]])
  assert_character(value[["headline"]])
  assert_no_missing_values(value[["headline"]])
  assert_character(value[["author"]])
  assert_no_missing_values(value[["author"]])
  assert_character(value[["source"]])
  assert_no_missing_values(value[["source"]])
  assert_character(value[["summary"]])
  assert_no_missing_values(value[["summary"]])
  assert_character(value[["url"]])
  assert_no_missing_values(value[["url"]])
  assert_character(value[["symbols"]])
  assert_datetime(value[["created_at"]])
  assert_no_missing_values(value[["created_at"]])
  assert_datetime(value[["updated_at"]])
  assert_no_missing_values(value[["updated_at"]])
  assert_character(value[["image_sizes"]])
  assert_character(value[["image_urls"]])
  return(value)
}

assert_args_AlpacaMarketData__get_crypto_orderbook <- function(symbols, loc) {
  assert_character(symbols)
  assert_no_missing_values(symbols)
  assert_scalar_character(loc)
  return(invisible(NULL))
}

assert_return_AlpacaMarketData__get_crypto_orderbook <- function(value) {
  assert_data_table(value)
  assert_has_columns(value, c("symbol", "side", "level", "price", "size", "timestamp"))
  assert_character(value[["symbol"]])
  assert_no_missing_values(value[["symbol"]])
  assert_character(value[["side"]])
  assert_no_missing_values(value[["side"]])
  assert_integer(value[["level"]])
  assert_no_missing_values(value[["level"]])
  assert_double(value[["price"]])
  assert_no_missing_values(value[["price"]])
  assert_double(value[["size"]])
  assert_no_missing_values(value[["size"]])
  assert_datetime(value[["timestamp"]])
  assert_no_missing_values(value[["timestamp"]])
  return(value)
}

assert_args_AlpacaMarketData__get_most_actives <- function(by, top) {
  if (!is.null(by)) {
    assert_scalar_character(by)
  }
  if (!is.null(top)) {
    assert_scalar_count(top)
    assert_between(top, lower = 1)
  }
  return(invisible(NULL))
}

assert_return_AlpacaMarketData__get_most_actives <- function(value) {
  assert_data_table(value)
  assert_has_columns(value, c("symbol", "volume", "trade_count"))
  assert_character(value[["symbol"]])
  assert_no_missing_values(value[["symbol"]])
  assert_count(value[["volume"]])
  assert_count(value[["trade_count"]])
  return(value)
}

assert_args_AlpacaMarketData__get_movers <- function(market_type, top) {
  assert_scalar_character(market_type)
  if (!is.null(top)) {
    assert_scalar_count(top)
    assert_between(top, lower = 1)
  }
  return(invisible(NULL))
}

assert_return_AlpacaMarketData__get_movers <- function(value) {
  assert_data_table(value)
  assert_has_columns(value, c("symbol", "percent_change", "change", "price", "direction"))
  assert_character(value[["symbol"]])
  assert_no_missing_values(value[["symbol"]])
  assert_double(value[["percent_change"]])
  assert_no_missing_values(value[["percent_change"]])
  assert_double(value[["change"]])
  assert_no_missing_values(value[["change"]])
  assert_double(value[["price"]])
  assert_no_missing_values(value[["price"]])
  assert_character(value[["direction"]])
  assert_no_missing_values(value[["direction"]])
  return(value)
}

assert_args_AlpacaOptions__initialize <- function(keys, base_url, data_base_url, async) {
  assert_list(keys)
  assert_scalar_character(base_url)
  assert_scalar_character(data_base_url)
  assert_scalar_logical(async)
  return(invisible(NULL))
}

assert_return_AlpacaOptions__initialize <- function(value) {
  assert_class(value, "AlpacaOptions")
  return(value)
}

assert_args_AlpacaOptions__get_contracts <- function(underlying_symbols, status, type, expiration_date, expiration_date_gte, expiration_date_lte, strike_price_gte, strike_price_lte, root_symbol, style, limit, page_token, show_deliverables, ppind) {
  if (!is.null(underlying_symbols)) {
    assert_scalar_character(underlying_symbols)
  }
  if (!is.null(status)) {
    assert_scalar_character(status)
  }
  if (!is.null(type)) {
    assert_scalar_character(type)
  }
  if (!is.null(expiration_date)) {
    assert_scalar_character(expiration_date)
  }
  if (!is.null(expiration_date_gte)) {
    assert_scalar_character(expiration_date_gte)
  }
  if (!is.null(expiration_date_lte)) {
    assert_scalar_character(expiration_date_lte)
  }
  if (!is.null(strike_price_gte)) {
    assert_scalar_double(strike_price_gte)
  }
  if (!is.null(strike_price_lte)) {
    assert_scalar_double(strike_price_lte)
  }
  if (!is.null(root_symbol)) {
    assert_scalar_character(root_symbol)
  }
  if (!is.null(style)) {
    assert_scalar_character(style)
  }
  if (!is.null(limit)) {
    assert_scalar_count(limit)
    assert_between(limit, lower = 1, upper = 10001, upper_inclusive = FALSE)
  }
  if (!is.null(page_token)) {
    assert_scalar_character(page_token)
  }
  if (!is.null(show_deliverables)) {
    assert_scalar_logical(show_deliverables)
  }
  if (!is.null(ppind)) {
    assert_scalar_logical(ppind)
  }
  return(invisible(NULL))
}

assert_return_AlpacaOptions__get_contracts <- function(value) {
  assert_data_table(value)
  assert_has_columns(value, c("id", "symbol", "name", "status", "tradable", "type", "strike_price", "expiration_date", "underlying_symbol", "style", "root_symbol", "size", "open_interest", "close_price"))
  assert_character(value[["id"]])
  assert_no_missing_values(value[["id"]])
  assert_character(value[["symbol"]])
  assert_no_missing_values(value[["symbol"]])
  assert_character(value[["name"]])
  assert_no_missing_values(value[["name"]])
  assert_character(value[["status"]])
  assert_no_missing_values(value[["status"]])
  assert_logical(value[["tradable"]])
  assert_no_missing_values(value[["tradable"]])
  assert_character(value[["type"]])
  assert_no_missing_values(value[["type"]])
  assert_character(value[["strike_price"]])
  assert_no_missing_values(value[["strike_price"]])
  assert_date(value[["expiration_date"]])
  assert_no_missing_values(value[["expiration_date"]])
  assert_character(value[["underlying_symbol"]])
  assert_no_missing_values(value[["underlying_symbol"]])
  assert_character(value[["style"]])
  assert_no_missing_values(value[["style"]])
  assert_character(value[["root_symbol"]])
  assert_no_missing_values(value[["root_symbol"]])
  assert_character(value[["size"]])
  assert_no_missing_values(value[["size"]])
  assert_character(value[["open_interest"]])
  assert_character(value[["close_price"]])
  return(value)
}

assert_args_AlpacaOptions__get_contract <- function(symbol_or_id) {
  assert_scalar_character(symbol_or_id)
  return(invisible(NULL))
}

assert_return_AlpacaOptions__get_contract <- function(value) {
  assert_data_table(value)
  assert_has_columns(value, c("id", "symbol", "name", "status", "tradable", "type", "strike_price", "expiration_date", "underlying_symbol", "style", "root_symbol", "size", "open_interest", "close_price"))
  assert_character(value[["id"]])
  assert_no_missing_values(value[["id"]])
  assert_character(value[["symbol"]])
  assert_no_missing_values(value[["symbol"]])
  assert_character(value[["name"]])
  assert_no_missing_values(value[["name"]])
  assert_character(value[["status"]])
  assert_no_missing_values(value[["status"]])
  assert_logical(value[["tradable"]])
  assert_no_missing_values(value[["tradable"]])
  assert_character(value[["type"]])
  assert_no_missing_values(value[["type"]])
  assert_character(value[["strike_price"]])
  assert_no_missing_values(value[["strike_price"]])
  assert_date(value[["expiration_date"]])
  assert_no_missing_values(value[["expiration_date"]])
  assert_character(value[["underlying_symbol"]])
  assert_no_missing_values(value[["underlying_symbol"]])
  assert_character(value[["style"]])
  assert_no_missing_values(value[["style"]])
  assert_character(value[["root_symbol"]])
  assert_no_missing_values(value[["root_symbol"]])
  assert_character(value[["size"]])
  assert_no_missing_values(value[["size"]])
  assert_character(value[["open_interest"]])
  assert_character(value[["close_price"]])
  return(value)
}

assert_args_AlpacaOptions__get_option_bars <- function(symbols, timeframe, start, end, limit, page_token, sort) {
  assert_scalar_character(symbols)
  assert_scalar_character(timeframe)
  if (!is.null(start)) {
    assert_scalar_character(start)
  }
  if (!is.null(end)) {
    assert_scalar_character(end)
  }
  if (!is.null(limit)) {
    assert_scalar_count(limit)
    assert_between(limit, lower = 1, upper = 10001, upper_inclusive = FALSE)
  }
  if (!is.null(page_token)) {
    assert_scalar_character(page_token)
  }
  if (!is.null(sort)) {
    assert_scalar_character(sort)
  }
  return(invisible(NULL))
}

assert_return_AlpacaOptions__get_option_bars <- function(value) {
  assert_data_table(value)
  assert_has_columns(value, c("timestamp", "open", "high", "low", "close", "volume", "trade_count", "vwap", "symbol"))
  assert_datetime(value[["timestamp"]])
  assert_no_missing_values(value[["timestamp"]])
  assert_double(value[["open"]])
  assert_no_missing_values(value[["open"]])
  assert_double(value[["high"]])
  assert_no_missing_values(value[["high"]])
  assert_double(value[["low"]])
  assert_no_missing_values(value[["low"]])
  assert_double(value[["close"]])
  assert_no_missing_values(value[["close"]])
  assert_double(value[["volume"]])
  assert_no_missing_values(value[["volume"]])
  assert_double(value[["trade_count"]])
  assert_no_missing_values(value[["trade_count"]])
  assert_double(value[["vwap"]])
  assert_no_missing_values(value[["vwap"]])
  assert_character(value[["symbol"]])
  assert_no_missing_values(value[["symbol"]])
  return(value)
}

assert_args_AlpacaOptions__get_option_trades <- function(symbols, start, end, limit, page_token, sort) {
  assert_scalar_character(symbols)
  if (!is.null(start)) {
    assert_scalar_character(start)
  }
  if (!is.null(end)) {
    assert_scalar_character(end)
  }
  if (!is.null(limit)) {
    assert_scalar_count(limit)
    assert_between(limit, lower = 1, upper = 10001, upper_inclusive = FALSE)
  }
  if (!is.null(page_token)) {
    assert_scalar_character(page_token)
  }
  if (!is.null(sort)) {
    assert_scalar_character(sort)
  }
  return(invisible(NULL))
}

assert_return_AlpacaOptions__get_option_trades <- function(value) {
  assert_data_table(value)
  assert_has_columns(value, c("timestamp", "price", "size", "exchange", "id", "conditions", "symbol"))
  assert_datetime(value[["timestamp"]])
  assert_no_missing_values(value[["timestamp"]])
  assert_double(value[["price"]])
  assert_no_missing_values(value[["price"]])
  assert_integer(value[["size"]])
  assert_no_missing_values(value[["size"]])
  assert_character(value[["exchange"]])
  assert_no_missing_values(value[["exchange"]])
  assert_double(value[["id"]])
  assert_no_missing_values(value[["id"]])
  assert_character(value[["conditions"]])
  assert_character(value[["symbol"]])
  assert_no_missing_values(value[["symbol"]])
  return(value)
}

assert_args_AlpacaOptions__get_option_latest_quotes <- function(symbols, feed) {
  assert_scalar_character(symbols)
  if (!is.null(feed)) {
    assert_scalar_character(feed)
  }
  return(invisible(NULL))
}

assert_return_AlpacaOptions__get_option_latest_quotes <- function(value) {
  assert_data_table(value)
  assert_has_columns(value, c("timestamp", "ask_exchange", "ask_price", "ask_size", "bid_exchange", "bid_price", "bid_size", "conditions", "symbol"))
  assert_datetime(value[["timestamp"]])
  assert_no_missing_values(value[["timestamp"]])
  assert_character(value[["ask_exchange"]])
  assert_no_missing_values(value[["ask_exchange"]])
  assert_double(value[["ask_price"]])
  assert_integer(value[["ask_size"]])
  assert_no_missing_values(value[["ask_size"]])
  assert_character(value[["bid_exchange"]])
  assert_no_missing_values(value[["bid_exchange"]])
  assert_double(value[["bid_price"]])
  assert_integer(value[["bid_size"]])
  assert_no_missing_values(value[["bid_size"]])
  assert_character(value[["conditions"]])
  assert_character(value[["symbol"]])
  assert_no_missing_values(value[["symbol"]])
  return(value)
}

assert_args_AlpacaOptions__get_option_latest_trades <- function(symbols, feed) {
  assert_scalar_character(symbols)
  if (!is.null(feed)) {
    assert_scalar_character(feed)
  }
  return(invisible(NULL))
}

assert_return_AlpacaOptions__get_option_latest_trades <- function(value) {
  assert_data_table(value)
  assert_has_columns(value, c("timestamp", "price", "size", "exchange", "id", "conditions", "symbol"))
  assert_datetime(value[["timestamp"]])
  assert_no_missing_values(value[["timestamp"]])
  assert_double(value[["price"]])
  assert_no_missing_values(value[["price"]])
  assert_integer(value[["size"]])
  assert_no_missing_values(value[["size"]])
  assert_character(value[["exchange"]])
  assert_no_missing_values(value[["exchange"]])
  assert_double(value[["id"]])
  assert_no_missing_values(value[["id"]])
  assert_character(value[["conditions"]])
  assert_character(value[["symbol"]])
  assert_no_missing_values(value[["symbol"]])
  return(value)
}

assert_args_AlpacaOptions__get_option_snapshots <- function(symbols, feed, updated_since, limit, page_token) {
  assert_scalar_character(symbols)
  if (!is.null(feed)) {
    assert_scalar_character(feed)
  }
  if (!is.null(updated_since)) {
    assert_scalar_character(updated_since)
  }
  if (!is.null(limit)) {
    assert_scalar_count(limit)
    assert_between(limit, lower = 1, upper = 1001, upper_inclusive = FALSE)
  }
  if (!is.null(page_token)) {
    assert_scalar_character(page_token)
  }
  return(invisible(NULL))
}

assert_return_AlpacaOptions__get_option_snapshots <- function(value) {
  assert_data_table(value)
  assert_has_columns(value, c("latest_trade_timestamp", "latest_trade_price", "latest_trade_size", "latest_trade_conditions", "latest_quote_timestamp", "latest_quote_ask_price", "latest_quote_bid_price", "latest_quote_ask_size", "latest_quote_bid_size", "latest_quote_conditions", "symbol"))
  assert_datetime(value[["latest_trade_timestamp"]])
  assert_double(value[["latest_trade_price"]])
  assert_integer(value[["latest_trade_size"]])
  assert_character(value[["latest_trade_conditions"]])
  assert_datetime(value[["latest_quote_timestamp"]])
  assert_no_missing_values(value[["latest_quote_timestamp"]])
  assert_double(value[["latest_quote_ask_price"]])
  assert_double(value[["latest_quote_bid_price"]])
  assert_integer(value[["latest_quote_ask_size"]])
  assert_no_missing_values(value[["latest_quote_ask_size"]])
  assert_integer(value[["latest_quote_bid_size"]])
  assert_no_missing_values(value[["latest_quote_bid_size"]])
  assert_character(value[["latest_quote_conditions"]])
  assert_character(value[["symbol"]])
  assert_no_missing_values(value[["symbol"]])
  return(value)
}

assert_args_AlpacaOptions__get_option_chain <- function(underlying_symbol, type, expiration_date, expiration_date_gte, expiration_date_lte, strike_price_gte, strike_price_lte, root_symbol, feed, limit, updated_since, page_token) {
  assert_scalar_character(underlying_symbol)
  if (!is.null(type)) {
    assert_scalar_character(type)
  }
  if (!is.null(expiration_date)) {
    assert_scalar_character(expiration_date)
  }
  if (!is.null(expiration_date_gte)) {
    assert_scalar_character(expiration_date_gte)
  }
  if (!is.null(expiration_date_lte)) {
    assert_scalar_character(expiration_date_lte)
  }
  if (!is.null(strike_price_gte)) {
    assert_scalar_double(strike_price_gte)
  }
  if (!is.null(strike_price_lte)) {
    assert_scalar_double(strike_price_lte)
  }
  if (!is.null(root_symbol)) {
    assert_scalar_character(root_symbol)
  }
  if (!is.null(feed)) {
    assert_scalar_character(feed)
  }
  if (!is.null(limit)) {
    assert_scalar_count(limit)
    assert_between(limit, lower = 1, upper = 1001, upper_inclusive = FALSE)
  }
  if (!is.null(updated_since)) {
    assert_scalar_character(updated_since)
  }
  if (!is.null(page_token)) {
    assert_scalar_character(page_token)
  }
  return(invisible(NULL))
}

assert_return_AlpacaOptions__get_option_chain <- function(value) {
  assert_data_table(value)
  assert_has_columns(value, c("latest_trade_timestamp", "latest_trade_price", "latest_trade_size", "latest_trade_conditions", "latest_quote_timestamp", "latest_quote_ask_price", "latest_quote_bid_price", "latest_quote_ask_size", "latest_quote_bid_size", "latest_quote_conditions", "symbol"))
  assert_datetime(value[["latest_trade_timestamp"]])
  assert_double(value[["latest_trade_price"]])
  assert_integer(value[["latest_trade_size"]])
  assert_character(value[["latest_trade_conditions"]])
  assert_datetime(value[["latest_quote_timestamp"]])
  assert_no_missing_values(value[["latest_quote_timestamp"]])
  assert_double(value[["latest_quote_ask_price"]])
  assert_double(value[["latest_quote_bid_price"]])
  assert_integer(value[["latest_quote_ask_size"]])
  assert_no_missing_values(value[["latest_quote_ask_size"]])
  assert_integer(value[["latest_quote_bid_size"]])
  assert_no_missing_values(value[["latest_quote_bid_size"]])
  assert_character(value[["latest_quote_conditions"]])
  assert_character(value[["symbol"]])
  assert_no_missing_values(value[["symbol"]])
  return(value)
}

assert_args_AlpacaTrading__add_order <- function(symbol, side, type, time_in_force, qty, notional, limit_price, stop_price, trail_price, trail_percent, extended_hours, client_order_id, order_class, take_profit, stop_loss, position_intent, legs, advanced_instructions) {
  if (!is.null(symbol)) {
    assert_scalar_character(symbol)
  }
  if (!is.null(side)) {
    assert_scalar_character(side)
  }
  assert_scalar_character(type)
  assert_scalar_character(time_in_force)
  if (!is.null(qty)) {
    assert_scalar_double(qty)
  }
  if (!is.null(notional)) {
    assert_scalar_double(notional)
  }
  if (!is.null(limit_price)) {
    assert_scalar_double(limit_price)
  }
  if (!is.null(stop_price)) {
    assert_scalar_double(stop_price)
  }
  if (!is.null(trail_price)) {
    assert_scalar_double(trail_price)
  }
  if (!is.null(trail_percent)) {
    assert_scalar_double(trail_percent)
  }
  if (!is.null(extended_hours)) {
    assert_scalar_logical(extended_hours)
  }
  if (!is.null(client_order_id)) {
    assert_scalar_character(client_order_id)
  }
  if (!is.null(order_class)) {
    assert_scalar_character(order_class)
  }
  if (!is.null(take_profit)) {
    assert_list(take_profit)
  }
  if (!is.null(stop_loss)) {
    assert_list(stop_loss)
  }
  if (!is.null(position_intent)) {
    assert_scalar_character(position_intent)
  }
  if (!is.null(legs)) {
    assert_list(legs)
  }
  if (!is.null(advanced_instructions)) {
    assert_list(advanced_instructions)
  }
  return(invisible(NULL))
}

assert_return_AlpacaTrading__add_order <- function(value) {
  assert_data_table(value)
  assert_has_columns(value, c("id", "symbol", "side", "type", "status", "qty", "filled_qty", "created_at", "leg_index", "parent_order_id"))
  assert_character(value[["id"]])
  assert_no_missing_values(value[["id"]])
  assert_character(value[["symbol"]])
  assert_no_missing_values(value[["symbol"]])
  assert_character(value[["side"]])
  assert_no_missing_values(value[["side"]])
  assert_character(value[["type"]])
  assert_no_missing_values(value[["type"]])
  assert_character(value[["status"]])
  assert_no_missing_values(value[["status"]])
  assert_character(value[["qty"]])
  assert_no_missing_values(value[["qty"]])
  assert_character(value[["filled_qty"]])
  assert_no_missing_values(value[["filled_qty"]])
  assert_datetime(value[["created_at"]])
  assert_no_missing_values(value[["created_at"]])
  assert_integer(value[["leg_index"]])
  assert_character(value[["parent_order_id"]])
  return(value)
}

assert_args_AlpacaTrading__get_orders <- function(status, limit, after, until, direction, nested, symbols, side, asset_class, before_order_id, after_order_id) {
  if (!is.null(status)) {
    assert_scalar_character(status)
  }
  if (!is.null(limit)) {
    assert_scalar_count(limit)
    assert_between(limit, lower = 1)
  }
  if (!is.null(after)) {
    assert_scalar_character(after)
  }
  if (!is.null(until)) {
    assert_scalar_character(until)
  }
  if (!is.null(direction)) {
    assert_scalar_character(direction)
  }
  if (!is.null(nested)) {
    assert_scalar_logical(nested)
  }
  if (!is.null(symbols)) {
    assert_scalar_character(symbols)
  }
  if (!is.null(side)) {
    assert_scalar_character(side)
  }
  if (!is.null(asset_class)) {
    assert_scalar_character(asset_class)
  }
  if (!is.null(before_order_id)) {
    assert_scalar_character(before_order_id)
  }
  if (!is.null(after_order_id)) {
    assert_scalar_character(after_order_id)
  }
  return(invisible(NULL))
}

assert_return_AlpacaTrading__get_orders <- function(value) {
  assert_data_table(value)
  assert_has_columns(value, c("id", "symbol", "side", "type", "status", "qty", "filled_qty", "created_at", "leg_index", "parent_order_id"))
  assert_character(value[["id"]])
  assert_no_missing_values(value[["id"]])
  assert_character(value[["symbol"]])
  assert_no_missing_values(value[["symbol"]])
  assert_character(value[["side"]])
  assert_no_missing_values(value[["side"]])
  assert_character(value[["type"]])
  assert_no_missing_values(value[["type"]])
  assert_character(value[["status"]])
  assert_no_missing_values(value[["status"]])
  assert_character(value[["qty"]])
  assert_no_missing_values(value[["qty"]])
  assert_character(value[["filled_qty"]])
  assert_no_missing_values(value[["filled_qty"]])
  assert_datetime(value[["created_at"]])
  assert_no_missing_values(value[["created_at"]])
  assert_integer(value[["leg_index"]])
  assert_character(value[["parent_order_id"]])
  return(value)
}

assert_args_AlpacaTrading__get_order <- function(order_id, nested) {
  assert_scalar_character(order_id)
  if (!is.null(nested)) {
    assert_scalar_logical(nested)
  }
  return(invisible(NULL))
}

assert_return_AlpacaTrading__get_order <- function(value) {
  assert_data_table(value)
  assert_has_columns(value, c("id", "symbol", "side", "type", "status", "qty", "filled_qty", "created_at", "leg_index", "parent_order_id"))
  assert_character(value[["id"]])
  assert_no_missing_values(value[["id"]])
  assert_character(value[["symbol"]])
  assert_no_missing_values(value[["symbol"]])
  assert_character(value[["side"]])
  assert_no_missing_values(value[["side"]])
  assert_character(value[["type"]])
  assert_no_missing_values(value[["type"]])
  assert_character(value[["status"]])
  assert_no_missing_values(value[["status"]])
  assert_character(value[["qty"]])
  assert_no_missing_values(value[["qty"]])
  assert_character(value[["filled_qty"]])
  assert_no_missing_values(value[["filled_qty"]])
  assert_datetime(value[["created_at"]])
  assert_no_missing_values(value[["created_at"]])
  assert_integer(value[["leg_index"]])
  assert_character(value[["parent_order_id"]])
  return(value)
}

assert_args_AlpacaTrading__get_order_by_client_id <- function(client_order_id) {
  assert_scalar_character(client_order_id)
  return(invisible(NULL))
}

assert_return_AlpacaTrading__get_order_by_client_id <- function(value) {
  assert_data_table(value)
  assert_has_columns(value, c("id", "symbol", "side", "type", "status", "qty", "filled_qty", "created_at", "leg_index", "parent_order_id"))
  assert_character(value[["id"]])
  assert_no_missing_values(value[["id"]])
  assert_character(value[["symbol"]])
  assert_no_missing_values(value[["symbol"]])
  assert_character(value[["side"]])
  assert_no_missing_values(value[["side"]])
  assert_character(value[["type"]])
  assert_no_missing_values(value[["type"]])
  assert_character(value[["status"]])
  assert_no_missing_values(value[["status"]])
  assert_character(value[["qty"]])
  assert_no_missing_values(value[["qty"]])
  assert_character(value[["filled_qty"]])
  assert_no_missing_values(value[["filled_qty"]])
  assert_datetime(value[["created_at"]])
  assert_no_missing_values(value[["created_at"]])
  assert_integer(value[["leg_index"]])
  assert_character(value[["parent_order_id"]])
  return(value)
}

assert_args_AlpacaTrading__modify_order <- function(order_id, qty, notional, time_in_force, limit_price, stop_price, trail, client_order_id, advanced_instructions) {
  assert_scalar_character(order_id)
  if (!is.null(qty)) {
    assert_scalar_double(qty)
  }
  if (!is.null(notional)) {
    assert_scalar_double(notional)
  }
  if (!is.null(time_in_force)) {
    assert_scalar_character(time_in_force)
  }
  if (!is.null(limit_price)) {
    assert_scalar_double(limit_price)
  }
  if (!is.null(stop_price)) {
    assert_scalar_double(stop_price)
  }
  if (!is.null(trail)) {
    assert_scalar_double(trail)
  }
  if (!is.null(client_order_id)) {
    assert_scalar_character(client_order_id)
  }
  if (!is.null(advanced_instructions)) {
    assert_list(advanced_instructions)
  }
  return(invisible(NULL))
}

assert_return_AlpacaTrading__modify_order <- function(value) {
  assert_data_table(value)
  assert_has_columns(value, c("id", "symbol", "side", "type", "status", "qty", "filled_qty", "created_at", "leg_index", "parent_order_id"))
  assert_character(value[["id"]])
  assert_no_missing_values(value[["id"]])
  assert_character(value[["symbol"]])
  assert_no_missing_values(value[["symbol"]])
  assert_character(value[["side"]])
  assert_no_missing_values(value[["side"]])
  assert_character(value[["type"]])
  assert_no_missing_values(value[["type"]])
  assert_character(value[["status"]])
  assert_no_missing_values(value[["status"]])
  assert_character(value[["qty"]])
  assert_no_missing_values(value[["qty"]])
  assert_character(value[["filled_qty"]])
  assert_no_missing_values(value[["filled_qty"]])
  assert_datetime(value[["created_at"]])
  assert_no_missing_values(value[["created_at"]])
  assert_integer(value[["leg_index"]])
  assert_character(value[["parent_order_id"]])
  return(value)
}

assert_args_AlpacaTrading__cancel_order <- function(order_id) {
  assert_scalar_character(order_id)
  return(invisible(NULL))
}

assert_return_AlpacaTrading__cancel_order <- function(value) {
  assert_data_table(value)
  assert_has_columns(value, c("order_id", "status"))
  assert_character(value[["order_id"]])
  assert_no_missing_values(value[["order_id"]])
  assert_character(value[["status"]])
  assert_no_missing_values(value[["status"]])
  return(value)
}

assert_return_AlpacaTrading__cancel_all_orders <- function(value) {
  assert_data_table(value)
  return(value)
}

assert_args_alpaca_backfill_bars <- function(symbols, timeframes, start, end, path, adjustment, feed, sleep, keys, data_base_url) {
  assert_character(symbols)
  assert_no_missing_values(symbols)
  assert_character(timeframes)
  assert_no_missing_values(timeframes)
  assert_any_of(
    start,
    function(.x) {
      assert_datetime(.x)
      assert_no_missing_values(.x)
    },
    function(.x) {
      assert_character(.x)
      assert_no_missing_values(.x)
    }
  )
  assert_any_of(
    end,
    function(.x) {
      assert_datetime(.x)
      assert_no_missing_values(.x)
    },
    function(.x) {
      assert_character(.x)
      assert_no_missing_values(.x)
    }
  )
  assert_scalar_character(path)
  assert_scalar_character(adjustment)
  if (!is.null(feed)) {
    assert_scalar_character(feed)
  }
  assert_scalar_double(sleep)
  assert_between(sleep, lower = 0, upper = Inf, upper_inclusive = FALSE)
  assert_list(keys)
  assert_scalar_character(data_base_url)
  return(invisible(NULL))
}

assert_return_alpaca_backfill_bars <- function(value) {
  assert_class(value, "data.table")
  return(value)
}

assert_args_wrap_list_fields <- function(x) {
  assert_list(x)
  return(invisible(NULL))
}

assert_return_wrap_list_fields <- function(value) {
  assert_list(value)
  return(value)
}

assert_args_rfc3339_to_datetime <- function(x) {
  if (!is.null(x)) {
    assert_character(x)
  }
  return(invisible(NULL))
}

assert_return_rfc3339_to_datetime <- function(value) {
  assert_datetime(value)
  return(value)
}

assert_args_coerce_cols <- function(dt, cols, fn) {
  assert_class(dt, "data.table")
  assert_character(cols)
  assert_no_missing_values(cols)
  assert_function(fn)
  return(invisible(NULL))
}

assert_return_coerce_cols <- function(value) {
  assert_class(value, "data.table")
  return(value)
}

assert_args_combine_et_datetime <- function(date, time) {
  assert_character(date)
  assert_character(time)
  return(invisible(NULL))
}

assert_return_combine_et_datetime <- function(value) {
  assert_datetime(value)
  return(value)
}

assert_args_hhmm_to_hh_mm <- function(x) {
  assert_character(x)
  return(invisible(NULL))
}

assert_return_hhmm_to_hh_mm <- function(value) {
  assert_character(value)
  return(value)
}

assert_args_parse_bars <- function(bars) {
  if (!is.null(bars)) {
    assert_list(bars)
  }
  return(invisible(NULL))
}

assert_return_parse_bars <- function(value) {
  assert_class(value, "data.table")
  return(value)
}

assert_args_parse_multi_bars_items <- function(items) {
  if (!is.null(items)) {
    assert_list(items)
  }
  return(invisible(NULL))
}

assert_return_parse_multi_bars_items <- function(value) {
  assert_class(value, "data.table")
  return(value)
}

assert_args_parse_trades <- function(trades) {
  if (!is.null(trades)) {
    assert_list(trades)
  }
  return(invisible(NULL))
}

assert_return_parse_trades <- function(value) {
  assert_class(value, "data.table")
  return(value)
}

assert_args_parse_quotes <- function(quotes) {
  if (!is.null(quotes)) {
    assert_list(quotes)
  }
  return(invisible(NULL))
}

assert_return_parse_quotes <- function(value) {
  assert_class(value, "data.table")
  return(value)
}

assert_args_parse_snapshot <- function(snapshot) {
  if (!is.null(snapshot)) {
    assert_list(snapshot)
  }
  return(invisible(NULL))
}

assert_return_parse_snapshot <- function(value) {
  assert_class(value, "data.table")
  return(value)
}

assert_args_parse_news <- function(news_items) {
  if (!is.null(news_items)) {
    assert_list(news_items)
  }
  return(invisible(NULL))
}

assert_return_parse_news <- function(value) {
  assert_class(value, "data.table")
  return(value)
}

assert_args_parse_watchlist <- function(wl) {
  if (!is.null(wl)) {
    assert_list(wl)
  }
  return(invisible(NULL))
}

assert_return_parse_watchlist <- function(value) {
  assert_class(value, "data.table")
  return(value)
}

assert_args_parse_asset <- function(x) {
  if (!is.null(x)) {
    assert_list(x)
  }
  return(invisible(NULL))
}

assert_return_parse_asset <- function(value) {
  assert_class(value, "data.table")
  return(value)
}

assert_args_parse_assets <- function(items) {
  if (!is.null(items)) {
    assert_list(items)
  }
  return(invisible(NULL))
}

assert_return_parse_assets <- function(value) {
  assert_class(value, "data.table")
  return(value)
}

assert_args_parse_contract <- function(x) {
  if (!is.null(x)) {
    assert_list(x)
  }
  return(invisible(NULL))
}

assert_return_parse_contract <- function(value) {
  assert_class(value, "data.table")
  return(value)
}

assert_args_parse_contracts <- function(items) {
  if (!is.null(items)) {
    assert_list(items)
  }
  return(invisible(NULL))
}

assert_return_parse_contracts <- function(value) {
  assert_class(value, "data.table")
  return(value)
}

assert_args_parse_order <- function(x) {
  if (!is.null(x)) {
    assert_list(x)
  }
  return(invisible(NULL))
}

assert_return_parse_order <- function(value) {
  assert_class(value, "data.table")
  return(value)
}

assert_args_parse_orders <- function(items) {
  if (!is.null(items)) {
    assert_list(items)
  }
  return(invisible(NULL))
}

assert_return_parse_orders <- function(value) {
  assert_class(value, "data.table")
  return(value)
}

assert_args_alpaca_serialize_body <- function(body) {
  assert_list(body)
  return(invisible(NULL))
}

assert_return_alpaca_serialize_body <- function(value) {
  if (!is.null(value)) {
    assert_scalar_character(value)
  }
  return(value)
}

assert_args_alpaca_build_request <- function(base_url, endpoint, method, query, body, keys, .perform, .parser, is_async, timeout, simplifyVector) {
  assert_scalar_character(base_url)
  assert_scalar_character(endpoint)
  assert_scalar_character(method)
  assert_list(query)
  if (!is.null(body)) {
    assert_list(body)
  }
  if (!is.null(keys)) {
    assert_list(keys)
  }
  assert_function(.perform)
  assert_function(.parser)
  assert_scalar_logical(is_async)
  assert_scalar_double(timeout)
  assert_between(timeout, lower = 0, lower_inclusive = FALSE, upper = Inf, upper_inclusive = FALSE)
  assert_scalar_logical(simplifyVector)
  return(invisible(NULL))
}

assert_return_alpaca_build_request <- function(value) {
  return(value)
}

assert_args_alpaca_paginate <- function(base_url, endpoint, method, query, keys, .perform, .parser, is_async, items_field, max_pages, sleep, timeout) {
  assert_scalar_character(base_url)
  assert_scalar_character(endpoint)
  assert_scalar_character(method)
  assert_list(query)
  if (!is.null(keys)) {
    assert_list(keys)
  }
  assert_function(.perform)
  assert_function(.parser)
  assert_scalar_logical(is_async)
  if (!is.null(items_field)) {
    assert_scalar_character(items_field)
  }
  assert_any_of(
    max_pages,
    function(.x) {
      assert_scalar_double(.x)
      assert_between(.x, lower = 1)
    },
    function(.x) {
      assert_scalar_integer(.x)
      assert_between(.x, lower = 1)
    }
  )
  assert_scalar_double(sleep)
  assert_between(sleep, lower = 0, upper = Inf, upper_inclusive = FALSE)
  assert_scalar_double(timeout)
  assert_between(timeout, lower = 0, lower_inclusive = FALSE, upper = Inf, upper_inclusive = FALSE)
  return(invisible(NULL))
}

assert_return_alpaca_paginate <- function(value) {
  return(value)
}

assert_args_parse_alpaca_response <- function(resp, simplifyVector) {
  assert_class(resp, "httr2_response")
  assert_scalar_logical(simplifyVector)
  return(invisible(NULL))
}

assert_return_parse_alpaca_response <- function(value) {
  return(value)
}

assert_args_alpaca_fetch_bars <- function(symbol, timeframe, start, end, keys, data_base_url, .perform, is_async, adjustment, feed, limit_per_request, sleep) {
  assert_scalar_character(symbol)
  assert_scalar_character(timeframe)
  assert_any_of(
    start,
    function(.x) {
      assert_datetime(.x)
      assert_no_missing_values(.x)
    },
    function(.x) {
      assert_character(.x)
      assert_no_missing_values(.x)
    }
  )
  assert_any_of(
    end,
    function(.x) {
      assert_datetime(.x)
      assert_no_missing_values(.x)
    },
    function(.x) {
      assert_character(.x)
      assert_no_missing_values(.x)
    }
  )
  assert_list(keys)
  assert_scalar_character(data_base_url)
  assert_function(.perform)
  assert_scalar_logical(is_async)
  assert_scalar_character(adjustment)
  if (!is.null(feed)) {
    assert_scalar_character(feed)
  }
  assert_scalar_count(limit_per_request)
  assert_between(limit_per_request, lower = 1)
  assert_scalar_double(sleep)
  assert_between(sleep, lower = 0, upper = Inf, upper_inclusive = FALSE)
  return(invisible(NULL))
}

assert_return_alpaca_fetch_bars <- function(value) {
  assert_data_table(value)
  return(value)
}

assert_args_get_base_url <- function(url) {
  if (!is.null(url)) {
    assert_scalar_character(url)
  }
  return(invisible(NULL))
}

assert_return_get_base_url <- function(value) {
  assert_scalar_character(value)
  return(value)
}

assert_args_get_data_base_url <- function(url) {
  if (!is.null(url)) {
    assert_scalar_character(url)
  }
  return(invisible(NULL))
}

assert_return_get_data_base_url <- function(value) {
  assert_scalar_character(value)
  return(value)
}

assert_args_get_api_keys <- function(api_key, api_secret) {
  assert_scalar_character(api_key)
  assert_scalar_character(api_secret)
  return(invisible(NULL))
}

assert_return_get_api_keys <- function(value) {
  assert_list(value)
  assert_has_names(value, c("api_key", "api_secret"))
  assert_scalar_character(value[["api_key"]])
  assert_scalar_character(value[["api_secret"]])
  return(value)
}

assert_args_time_convert_from_alpaca <- function(x) {
  if (!is.null(x)) {
    assert_any_of(
      x,
      function(.x) {
        assert_character(.x)
        assert_no_missing_values(.x)
      },
      function(.x) {
        assert_logical(.x)
      }
    )
  }
  return(invisible(NULL))
}

assert_return_time_convert_from_alpaca <- function(value) {
  assert_datetime(value)
  return(value)
}

assert_args_time_convert_to_alpaca <- function(x) {
  if (!is.null(x)) {
    assert_any_of(
      x,
      function(.x) {
        assert_datetime(.x)
        assert_no_missing_values(.x)
      },
      function(.x) {
        assert_character(.x)
        assert_no_missing_values(.x)
      },
      function(.x) {
        assert_logical(.x)
        assert_no_missing_values(.x)
      }
    )
  }
  return(invisible(NULL))
}

assert_return_time_convert_to_alpaca <- function(value) {
  assert_character(value)
  return(value)
}

